<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Table Administration</name>
   <tag></tag>
   <elementGuidId>d8adab01-1d48-4701-95f7-11b06719e47a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_TreeViewMainMenut34']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_TreeViewMainMenut34</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b91bfdec-8b40-4dee-9ffb-64a0ecce828c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ctl00_TreeViewMainMenu_0</value>
      <webElementGuid>91fc0975-a5d9-480f-9fcc-240b34fbe80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/webportal/MemberPages/CBMG/CBMG_Tables/TableAdminMain.aspx</value>
      <webElementGuid>8110c15f-d678-43c6-b82a-83f313da44ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Table Administration</value>
      <webElementGuid>25515e3f-a155-45f7-8068-6de1cfc44af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_TreeViewMainMenut34</value>
      <webElementGuid>7a3ddbc3-466c-4341-b40e-9008a84613f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Table Administration</value>
      <webElementGuid>9220ed69-893f-493c-b560-5f76e9ebbc32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_TreeViewMainMenut34&quot;)</value>
      <webElementGuid>300def7d-fba1-4a68-b7b6-453c15693483</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_TreeViewMainMenut34']</value>
      <webElementGuid>7184b7a4-19c6-40f4-a55b-e443013c88c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_TreeViewMainMenun0Nodes']/table[9]/tbody/tr/td[4]/a</value>
      <webElementGuid>2aff4749-336a-4781-aa60-25cd01972aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Table Administration')]</value>
      <webElementGuid>836d0ad2-6d96-4e9a-8d37-53f437210fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ropes Report Last 3 days'])[1]/following::a[2]</value>
      <webElementGuid>20d184f3-ac9e-490d-aae0-6cf0efdf9238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ropes Report'])[1]/following::a[4]</value>
      <webElementGuid>47dfa4cd-66af-4a28-845d-81b766eba29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROPES BOSS'])[1]/preceding::a[2]</value>
      <webElementGuid>576c8df3-af99-4e35-a272-cb5d5121bf7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave Employee Package Tool'])[1]/preceding::a[6]</value>
      <webElementGuid>646c12b9-4824-4a8a-a990-2069ffcf9da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Table Administration']/parent::*</value>
      <webElementGuid>f8beeaa8-2c70-40e0-8474-ce91cd3f077c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/webportal/MemberPages/CBMG/CBMG_Tables/TableAdminMain.aspx')])[2]</value>
      <webElementGuid>4b0b3e6f-c9e4-489d-a001-8deaaefefdc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[9]/tbody/tr/td[4]/a</value>
      <webElementGuid>95c0d95d-dbc4-4400-9e98-4f5423980aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/webportal/MemberPages/CBMG/CBMG_Tables/TableAdminMain.aspx' and @title = 'Table Administration' and @id = 'ctl00_TreeViewMainMenut34' and (text() = 'Table Administration' or . = 'Table Administration')]</value>
      <webElementGuid>75d862e3-575c-464c-92b6-a05641e4b053</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
