<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Birth Date_leads.Birthdate</name>
   <tag></tag>
   <elementGuidId>bb78845d-7e9b-4114-9701-9f68ca2544c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leads_Birthdate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leads_Birthdate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94a5df86-3cf8-4054-b8fe-887e8ede806d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>0bb9942a-5e49-4162-bc26-98364bdddd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-text form-control-sm</value>
      <webElementGuid>9712bf77-6277-4b38-9b36-6015518b0039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leads_Birthdate</value>
      <webElementGuid>853753ab-c118-4fe8-a465-b0a28b9eef9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leads.Birthdate</value>
      <webElementGuid>6959840d-8638-4849-b450-88a144e4c080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1993-10-27</value>
      <webElementGuid>bce23f25-0721-4794-9199-d608554eb167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leads_Birthdate&quot;)</value>
      <webElementGuid>87c156ae-4baa-48c0-bbf6-524605347057</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leads_Birthdate']</value>
      <webElementGuid>86110e01-3d64-4688-a259-05b763609525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appDetailsView']/div[4]/div[4]/input</value>
      <webElementGuid>901e07c1-eed0-4d4b-b761-7eec377bedb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/input</value>
      <webElementGuid>0f4e7c53-45c8-4bac-8580-c1babea9c8c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'leads_Birthdate' and @name = 'leads.Birthdate']</value>
      <webElementGuid>3138d10c-da97-40d4-ae02-791669d4a11b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
