<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Birth Date(MMDD YYYY)_Birthdate</name>
   <tag></tag>
   <elementGuidId>82fcf384-feaf-4cac-a2cd-3626f7e15b0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Bdate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Bdate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>170acd32-db2f-49ac-bb26-56b139b28683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Bdate</value>
      <webElementGuid>e607a94e-80ec-4cd6-a95b-bdf18c6610a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-text form-control-sm</value>
      <webElementGuid>aca87b9a-b62a-42c5-981e-3931dcb221bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>b1fc9308-637e-45e8-ab65-6a4e82c5256e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eb1119b2-cad6-48b1-96ca-fbd731bc9aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Please enter your Birthdate</value>
      <webElementGuid>d8191f63-4f1b-4278-8d35-f37f0cc62e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Birthdate</value>
      <webElementGuid>39f05c54-037d-4381-9aac-868d75b76edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Bdate&quot;)</value>
      <webElementGuid>6cc88592-9a2a-43a0-abe2-ccbba75d1298</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Bdate']</value>
      <webElementGuid>6345a915-62f6-4ed6-831c-09684b44dc22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvPersonalInfo']/form/div[3]/div/input</value>
      <webElementGuid>a802ac89-0e9f-4ae3-b52e-4cb826a5cd96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>c0b857a8-4135-4791-b039-02d894005453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Bdate' and @type = 'date' and @name = 'Birthdate']</value>
      <webElementGuid>036db42e-1a72-48d6-a03d-2f74b9e3d46d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
