<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Table Administration</name>
   <tag></tag>
   <elementGuidId>162b64c4-f26a-41d7-a7be-b8dbc97b2027</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_TreeViewMainMenut34']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_TreeViewMainMenut34</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>46ed904f-5388-45c7-812a-ecd13d2ac08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ctl00_TreeViewMainMenu_0</value>
      <webElementGuid>592b2d53-932a-4972-b5fc-e5372a4c87b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/webportal/MemberPages/CBMG/CBMG_Tables/TableAdminMain.aspx</value>
      <webElementGuid>5e70c70c-6359-48de-9fa1-003445ee4440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Table Administration</value>
      <webElementGuid>a0b85136-2aa5-4f44-98c2-1abb89c599f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_TreeViewMainMenut34</value>
      <webElementGuid>b8d669b0-9126-478d-9866-b2f0fc9c5761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Table Administration</value>
      <webElementGuid>154169f8-25ee-46a5-8c99-8bd13e3b3156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_TreeViewMainMenut34&quot;)</value>
      <webElementGuid>8a21f745-d2df-41aa-bd92-d51690195cd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_TreeViewMainMenut34']</value>
      <webElementGuid>3cab1557-aab5-4eee-89fe-1042982da01d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_TreeViewMainMenun0Nodes']/table[9]/tbody/tr/td[4]/a</value>
      <webElementGuid>c8eb3167-9d10-49bf-87bc-b8e171a35b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Table Administration')]</value>
      <webElementGuid>2d6d9487-c4af-48a0-9116-89672a709237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ropes Report Last 3 days'])[1]/following::a[2]</value>
      <webElementGuid>ece8adf5-48b4-4fa7-b4e4-cdd4630674ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ropes Report'])[1]/following::a[4]</value>
      <webElementGuid>0df6a987-623e-4996-999c-bf13860235dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROPES BOSS'])[1]/preceding::a[2]</value>
      <webElementGuid>9c66df75-b429-4931-9fc3-49cce00a0355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave Employee Package Tool'])[1]/preceding::a[6]</value>
      <webElementGuid>386f3f76-0dcd-45da-be1a-89cec91d5ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Table Administration']/parent::*</value>
      <webElementGuid>4c81aa8c-3143-45bd-ac13-28dc907a5580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/webportal/MemberPages/CBMG/CBMG_Tables/TableAdminMain.aspx')])[2]</value>
      <webElementGuid>37db9d79-a909-44fd-bc3e-e2c9bbf09cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[9]/tbody/tr/td[4]/a</value>
      <webElementGuid>606ffb33-91c7-4cfb-8698-1e14a2a8b100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/webportal/MemberPages/CBMG/CBMG_Tables/TableAdminMain.aspx' and @title = 'Table Administration' and @id = 'ctl00_TreeViewMainMenut34' and (text() = 'Table Administration' or . = 'Table Administration')]</value>
      <webElementGuid>827d053e-0b91-4276-88e2-00749bcec637</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
