<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Select city of residence_dropdown-toggle</name>
   <tag></tag>
   <elementGuidId>c1c5be9b-5dc3-4bda-a9fc-b53cf3421715</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ngx-select[name=&quot;permanentCityOfResidence&quot;] > div.ngx-select.dropdown > div.ngx-select__selected > div.ngx-select__toggle.btn.form-control > span.ngx-select__toggle-buttons > i.dropdown-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/ngx-select/div/div[2]/div/span[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>6b26e009-bd60-42ab-b61c-804b74a3ecce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle</value>
      <webElementGuid>25c9ac6c-3b89-4e3a-9171-82c9f0ad5f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-dhp-layout[1]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;dhp-layout&quot;]/app-application-view[1]/main[1]/application-form[1]/div[@class=&quot;main-container&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;form-container&quot;]/div[@class=&quot;application-form&quot;]/main[1]/div[@class=&quot;card-body&quot;]/section[@class=&quot;main-form&quot;]/div[@class=&quot;pt-3&quot;]/app-personal-info[1]/main[1]/form[@class=&quot;form-sm ng-valid ng-touched ng-dirty&quot;]/div[@class=&quot;form-section&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;form-group col-sm-5&quot;]/ngx-select[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;ngx-select dropdown&quot;]/div[@class=&quot;ngx-select__selected&quot;]/div[@class=&quot;ngx-select__toggle btn form-control&quot;]/span[@class=&quot;ngx-select__toggle-buttons&quot;]/i[@class=&quot;dropdown-toggle&quot;]</value>
      <webElementGuid>27c6650e-412a-44e9-82ee-b986701af4f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ngx-select/div/div[2]/div/span[2]/i</value>
      <webElementGuid>1d94069e-5291-4a05-9504-67e037896899</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
