<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Assigned to Me</name>
   <tag></tag>
   <elementGuidId>d15034af-14b4-432d-aa0e-b5d48c9b97fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dropdownAssignment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropdownAssignment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>de2dda75-5b54-4d38-9249-160280869a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3a7a2e5d-5473-46ad-a12a-eb0f92fbfb65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdownAssignment</value>
      <webElementGuid>a1bb5504-da3e-4d63-b892-27476c194ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle btn btn-faded</value>
      <webElementGuid>d685e774-12fb-4060-9bb1-1643c0867ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>be38ca1b-25e4-406f-b39c-f18b84b0fec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Assigned to Me </value>
      <webElementGuid>4c9db9a8-098f-475f-bda3-012e588c3ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdownAssignment&quot;)</value>
      <webElementGuid>a1f32d6a-b5fa-4351-9546-a540e3b03cbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='dropdownAssignment']</value>
      <webElementGuid>a8030ff6-2aad-49a0-aa32-9cbf35258005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignment'])[1]/following::button[1]</value>
      <webElementGuid>cbc466ab-b64b-4847-9b4b-396f98393a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non-Agent'])[1]/following::button[1]</value>
      <webElementGuid>e5393d93-4fba-4973-bdd9-d148e86ca532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Applicants'])[1]/preceding::button[1]</value>
      <webElementGuid>71129f07-bff6-4af8-b47a-b19c2e4e7877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assigned to Me'])[2]/preceding::button[1]</value>
      <webElementGuid>4a4b86da-fcb2-425a-a6e0-fb0f55ab2073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Assigned to Me']/parent::*</value>
      <webElementGuid>6131482f-2f3a-43c8-8b1e-efff24f06382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>eb6f2d5d-6299-4c43-909b-118815c457c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'dropdownAssignment' and (text() = ' Assigned to Me ' or . = ' Assigned to Me ')]</value>
      <webElementGuid>78b718dc-efd6-4a27-85e0-f1843f400c76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
