<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_---Select---ScreenerRecruiter</name>
   <tag></tag>
   <elementGuidId>1fee1b75-3e56-4c3a-82b9-0f6218a7857f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dvCBMG_UserGroups_ddlUserType2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dvCBMG_UserGroups_ddlUserType2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b816cf57-260c-4214-92f5-b314082948fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dvCBMG_UserGroups$ddlUserType2</value>
      <webElementGuid>4f347f5f-0b07-4d93-aa2b-88671d9906d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dvCBMG_UserGroups_ddlUserType2</value>
      <webElementGuid>d4eb61bc-fc96-4936-9ad6-17fbaca831cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ee3f5b7-3f51-4ba4-856e-37d8a22a35df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				&lt;---Select--->
				Screener
				Recruiter

			</value>
      <webElementGuid>c9c3a988-41f6-498a-af5d-7449137be204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dvCBMG_UserGroups_ddlUserType2&quot;)</value>
      <webElementGuid>592e2845-8823-4228-afb5-cdc0fd40b138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PostDeployment/ScreenerMaintenance/Add_Screener/Page_247 IRIS - Table Administration/iframe_Table Title_ctl00_ContentPlaceHolder_3b72f3</value>
      <webElementGuid>4c13bf4b-3e46-40ba-8abc-e7ce8d26666c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dvCBMG_UserGroups_ddlUserType2']</value>
      <webElementGuid>6216bc0e-1c03-4b2d-8d5f-2a14d01e773c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dvCBMG_UserGroups']/tbody/tr[4]/td[2]/select</value>
      <webElementGuid>637d5777-9f28-44dd-b1ba-e4f718a6d623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Type'])[1]/following::select[1]</value>
      <webElementGuid>6c23a006-c294-4f4d-b059-cd82c9be6644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Name'])[1]/following::select[1]</value>
      <webElementGuid>e5d923ae-a4ce-4318-b47c-7b0349b02388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is Active'])[1]/preceding::select[1]</value>
      <webElementGuid>d7f5f437-0d3d-4c37-8053-751d2d26aeed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Userid'])[2]/preceding::select[1]</value>
      <webElementGuid>c7cdb161-178a-4c24-84ba-4381c2b14619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/select</value>
      <webElementGuid>dcf81d3b-f1e0-4edc-9d26-c1aef8baeadc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'dvCBMG_UserGroups$ddlUserType2' and @id = 'dvCBMG_UserGroups_ddlUserType2' and (text() = '
				&lt;---Select--->
				Screener
				Recruiter

			' or . = '
				&lt;---Select--->
				Screener
				Recruiter

			')]</value>
      <webElementGuid>8cad3786-b88a-4288-85a5-c6ee250b3fa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
