<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Internet Speed (jpg,jpeg,png)_UploadSpeedFile</name>
   <tag></tag>
   <elementGuidId>6af0d899-05a6-4d79-adf0-e30cb4721290</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='USFile']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#USFile</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68f19280-ac75-4047-b1a8-15ffddd430ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>USFile</value>
      <webElementGuid>86e03161-8677-4644-93db-b26993a0c56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>validateImg(this.value)</value>
      <webElementGuid>a2b2b5ce-faff-440e-ad75-1f2206fe5468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>1eabd131-52dc-43da-9c8f-278d2742e678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>6d46f8c0-3e0c-4752-ab50-bb933a987d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UploadSpeedFile</value>
      <webElementGuid>4eaa7c20-5542-448e-ac25-d70f23c6c4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;USFile&quot;)</value>
      <webElementGuid>e4b6b941-43e5-4ea5-a41b-778beb7da2d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='USFile']</value>
      <webElementGuid>e2f72c59-0e53-4363-89d6-f51f2a9b68e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmUpload']/div/div[3]/input</value>
      <webElementGuid>d08fe0b8-d6bf-4348-a176-4a376d9fbe9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[3]/input</value>
      <webElementGuid>65e345e3-7b5b-4fad-bd5b-531d2597831c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'USFile' and @type = 'file' and @name = 'UploadSpeedFile']</value>
      <webElementGuid>6c5f560b-c7a8-4e9d-be41-b93d0c5752bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
