<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Logout_nameSearch</name>
   <tag></tag>
   <elementGuidId>794c6bc6-c987-4b76-8ef4-2c338dc681ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nameSearch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nameSearch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>16977ae8-8bf2-4015-985d-267541a8daaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70be3e11-ee7e-4be8-9018-43fafca54749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for Names..</value>
      <webElementGuid>e9d32aa6-3d4e-4915-afca-fba3363a7e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-text</value>
      <webElementGuid>ff8f8953-344b-4a77-b329-050ead254346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.removeAttribute('readonly');</value>
      <webElementGuid>ebafb2f5-006f-4099-a447-f978288077d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nameSearch</value>
      <webElementGuid>756b1e48-0fa3-4ab3-99fe-41dcc7cdc689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nameSearch</value>
      <webElementGuid>497941e9-2388-4dc0-85ee-5367fe048045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nameSearch&quot;)</value>
      <webElementGuid>89990057-4396-4a27-813e-cf70832a1bf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nameSearch']</value>
      <webElementGuid>fc9d70a7-1f60-4e3a-9570-3f45d12d2c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmFilterRecipients']/div/div/div/div/input</value>
      <webElementGuid>eafde6b9-792d-4d43-89cd-d45015f8b60e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>3a270941-58d4-41cc-b604-1f4cfc31d7fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search for Names..' and @id = 'nameSearch' and @name = 'nameSearch']</value>
      <webElementGuid>7ded176a-16a8-45c5-9e0b-f9727ece72cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
