<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Table Title_ctl00_ContentPlaceHolder_3b72f3</name>
   <tag></tag>
   <elementGuidId>4e9a0077-e0ca-42ce-89cf-69d6c0b8c30c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ctl00_ContentPlaceHolder1_Frame1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_Frame1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2e3ece79-aa71-4466-adff-3b3022a754e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_Frame1</value>
      <webElementGuid>b0396326-638f-4348-a1fb-845e948b635d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1200</value>
      <webElementGuid>955e0a8a-4646-4053-b5df-d087a7fedcbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>5fb3686a-e244-4e08-9828-eedad72dc8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>CBMG_UserGroups.aspx</value>
      <webElementGuid>c3200190-f455-4c19-bbb2-15616bf38971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7165ac03-bd77-4bf4-b55c-3ef71277f5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_Frame1&quot;)</value>
      <webElementGuid>afd96f9e-17e0-45c2-982c-3ac4d27855b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ctl00_ContentPlaceHolder1_Frame1']</value>
      <webElementGuid>99843e4f-3c2d-431e-84bb-b23b430008fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/table[2]/tbody/tr[4]/td/iframe</value>
      <webElementGuid>da251073-8da8-45bd-a812-80ba1cd43050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>40097a72-fd39-4327-b674-b05a4782cabf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ctl00_ContentPlaceHolder1_Frame1' and @src = 'CBMG_UserGroups.aspx']</value>
      <webElementGuid>c0c58178-2968-41ae-a6ba-e5c28addfa99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
