<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Table Administration</name>
   <tag></tag>
   <elementGuidId>470b5cf5-3e28-4409-8d51-715a72599813</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_TreeViewMainMenut34']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_TreeViewMainMenut34</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>556fcb9a-a9e3-4b0d-938d-4f4853025f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ctl00_TreeViewMainMenu_0</value>
      <webElementGuid>ca36e2c4-c567-4e3b-b322-4cad8785b2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/webportal/MemberPages/CBMG/CBMG_Tables/TableAdminMain.aspx</value>
      <webElementGuid>ac01a157-5623-4e17-a4ba-b77ae3f4a662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Table Administration</value>
      <webElementGuid>4c215ac8-9097-4d91-a8af-03dd2cc4100d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_TreeViewMainMenut34</value>
      <webElementGuid>61122a87-729c-4487-a83e-3fc80c80b3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Table Administration</value>
      <webElementGuid>c2a05883-4dbb-4b4b-9f23-1abc5f7da232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_TreeViewMainMenut34&quot;)</value>
      <webElementGuid>342be8ac-e3ef-4b22-aa89-f6b7d82197ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_TreeViewMainMenut34']</value>
      <webElementGuid>28efba5b-e0f4-4154-a6a3-e387bb98b9a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_TreeViewMainMenun0Nodes']/table[9]/tbody/tr/td[4]/a</value>
      <webElementGuid>6f68af45-8a0e-4567-ab55-34381c2c9395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Table Administration')]</value>
      <webElementGuid>4b752fb2-e3d2-4ac6-91b9-bb5eb42d6fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ropes Report Last 3 days'])[1]/following::a[2]</value>
      <webElementGuid>6d5a5d9e-6c23-4405-ac95-f1c8cc51a27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ropes Report'])[1]/following::a[4]</value>
      <webElementGuid>ae403dd5-0e73-419d-afb1-1c58a21b9cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROPES BOSS'])[1]/preceding::a[2]</value>
      <webElementGuid>e8edc8ea-d432-4706-aae0-688639794f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave Employee Package Tool'])[1]/preceding::a[6]</value>
      <webElementGuid>a8a104db-f9db-4c4b-bfbe-cd0eaff597c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Table Administration']/parent::*</value>
      <webElementGuid>72a42390-dcd4-4974-b732-ce856bf25756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/webportal/MemberPages/CBMG/CBMG_Tables/TableAdminMain.aspx')])[2]</value>
      <webElementGuid>cdd5c376-ce7e-4574-893b-7523f6ca5a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[9]/tbody/tr/td[4]/a</value>
      <webElementGuid>efbb0e9b-5bc6-46b0-acf8-f705036804b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/webportal/MemberPages/CBMG/CBMG_Tables/TableAdminMain.aspx' and @title = 'Table Administration' and @id = 'ctl00_TreeViewMainMenut34' and (text() = 'Table Administration' or . = 'Table Administration')]</value>
      <webElementGuid>b29a1c74-49e7-4fc4-825a-d30358001043</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
