<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FB Profile URL_FBProfileId</name>
   <tag></tag>
   <elementGuidId>13b9514f-eca6-476a-a41e-af7fbd1fb579</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FBProfileId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FBProfileId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a11d805-9643-4141-93e5-0404c36b68bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-text form-control</value>
      <webElementGuid>04be706b-0e22-4123-9573-01995728b11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>79b97ece-52ef-4743-88d6-9178634705df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FBProfileId</value>
      <webElementGuid>399d9687-f83a-4524-bc23-fc09968b3198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FBProfileId</value>
      <webElementGuid>31c9556e-6e26-4f8d-b1f1-3227f944c0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FBProfileId&quot;)</value>
      <webElementGuid>66c0d30d-14b4-4361-8ff1-b9945fbd3b5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FBProfileId']</value>
      <webElementGuid>40e6de44-8b49-473f-b1f7-011d8d77af9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvPersonalInfo']/form/div[5]/div[4]/input</value>
      <webElementGuid>93e8be73-4ef7-4a60-bcb7-4d03a0da8b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>d308a60a-d98e-4e7c-a48b-4be3638619ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FBProfileId' and @name = 'FBProfileId']</value>
      <webElementGuid>423d5749-01b9-4d74-a7b8-ffa83825a792</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
