<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Birth Date(MMDD YYYY)_Birthdate</name>
   <tag></tag>
   <elementGuidId>c64095e4-edf8-476d-ad77-c9b189e5dbe4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Bdate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Bdate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a032c2d5-290e-4d02-952a-a4484edf6e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Bdate</value>
      <webElementGuid>a43ab1c2-79f1-4da3-b2f0-31fd8d27dbe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-text form-control-sm</value>
      <webElementGuid>2b057327-8b88-4f2c-bb55-127d56f13750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>f395f1ee-5c0f-4410-96cf-49e577b2e91c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e3345c51-ba64-4435-beef-dccf6b594e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Please enter your Birthdate</value>
      <webElementGuid>fd72bbf3-f2aa-4f1d-912f-ab887d90acd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Birthdate</value>
      <webElementGuid>d3a87834-8087-4ef9-99c9-b0da37be5abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Bdate&quot;)</value>
      <webElementGuid>cd45325d-264a-433f-a636-17beba3d0a7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Bdate']</value>
      <webElementGuid>25de8e30-5c03-43cf-a3ba-c352a807f844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvPersonalInfo']/form/div[3]/div/input</value>
      <webElementGuid>05cb3377-2c19-47e5-a51b-5d377450a6d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>d0530d02-1a70-4b81-b4d7-ce21e1520895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Bdate' and @type = 'date' and @name = 'Birthdate']</value>
      <webElementGuid>81336dcc-5e82-4f8b-8a24-71f85da660b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
