<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do you have your own Laptop or PC_HasLaptop</name>
   <tag></tag>
   <elementGuidId>713f4019-7f46-4e29-9827-107c216e0215</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rdHasLaptop1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rdHasLaptop1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2934989-cb63-4ba6-857d-fc85f7b7ac0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>fc2a70fe-06f9-4c0f-b697-69c5bab142e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>76fd4e2d-6d38-4128-aeaf-cacce4c28159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c23c0131-1dcb-4af4-8d62-f490c62edeb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdHasLaptop1</value>
      <webElementGuid>c99a338a-940d-4638-b6ed-18242051d630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0794a100-817f-4230-87ad-360582dd479b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The HasLaptop field is required.</value>
      <webElementGuid>37f0b2de-8cfe-4168-b18f-9f81fb4ffdee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>HasLaptop</value>
      <webElementGuid>58e92926-9f8a-438d-9a95-7ccebe97729d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdHasLaptop1&quot;)</value>
      <webElementGuid>cfd1922f-2494-4a76-8b69-63ff1119245c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rdHasLaptop1']</value>
      <webElementGuid>52076af5-c2c7-4303-9369-87c2f4034a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmApplicationDetails']/div[4]/div/div/input</value>
      <webElementGuid>2e896ea3-bc33-4cb8-9dea-6f76155f323d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>3cc71c68-cb86-4d8e-90ad-9a609a883a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'rdHasLaptop1' and @name = 'HasLaptop']</value>
      <webElementGuid>b6ce79b7-ac16-45cd-a41a-d1454c1a1727</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
