<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_edit</name>
   <tag></tag>
   <elementGuidId>92b76ec1-241d-4734-be15-fbb92a5d9ba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sms-conversation']/div/div[3]/p/button/mat-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-sm.sms-btn-message > mat-icon.mat-icon.notranslate.material-icons.mat-icon-inline.mat-icon-no-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>5922297f-eb5b-4af5-b700-0067d2a82874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a027d252-4f3f-4377-af6a-15dac0c68236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate material-icons mat-icon-inline mat-icon-no-color</value>
      <webElementGuid>afb101e8-73ef-4955-a377-1f8b549e7d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b6e5283a-167a-4e48-bf34-a878359b467a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>c68ed939-7fa3-4ca6-b52d-940cb7c35e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>edit</value>
      <webElementGuid>abd33cb4-bd79-415c-bba1-e8d091a784a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sms-conversation&quot;)/div[@class=&quot;imessage&quot;]/div[3]/p[@class=&quot;from-them&quot;]/button[@class=&quot;btn btn-sm sms-btn-message&quot;]/mat-icon[@class=&quot;mat-icon notranslate material-icons mat-icon-inline mat-icon-no-color&quot;]</value>
      <webElementGuid>d6e8d73f-b644-451b-a8b5-f770334e9576</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sms-conversation']/div/div[3]/p/button/mat-icon</value>
      <webElementGuid>1379dbda-e2f2-43b1-9050-3634269b2827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sent by : GINA ARCHIBAL'])[2]/following::mat-icon[1]</value>
      <webElementGuid>f697380a-d124-45e5-baa0-79042636d8e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sent by : GINA ARCHIBAL'])[1]/following::mat-icon[1]</value>
      <webElementGuid>50b1b21a-ae21-49fc-a866-26772549007a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit tag'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>a7423ff9-71f4-44f6-8531-d587101438a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sent by : 9978191997'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>d54254a8-532c-448b-99c0-1f5e0b330a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='edit']/parent::*</value>
      <webElementGuid>197a8f43-afe6-4100-a210-b070cd01a4b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p/button/mat-icon</value>
      <webElementGuid>df55cb43-c24e-440d-a441-ff723fd618b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'edit' or . = 'edit')]</value>
      <webElementGuid>512ee519-49c5-4f3f-ad2f-53c0e1908baf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
