<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_leads.Email</name>
   <tag></tag>
   <elementGuidId>89e66e09-b00c-4e28-ad91-a9a00f02bc43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leads_Email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#leads_Email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f10b355-6e79-4a46-95b1-83c96964ce12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>120d47a1-0661-4f35-9f11-b5d4aa879322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-text form-control-sm</value>
      <webElementGuid>069137ec-7adf-48c8-a8fc-0c23a1178972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leads_Email</value>
      <webElementGuid>71e9495a-94d4-46c4-9484-656ba7f96013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leads.Email</value>
      <webElementGuid>ddc708ae-ab9d-45ce-bde5-e13423761b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>jose.sanchez@247-inc.com</value>
      <webElementGuid>d8110c8e-2e01-4708-b1ac-5e2d5cbae1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leads_Email&quot;)</value>
      <webElementGuid>73f06de4-17eb-46a1-bd8a-982634152b04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leads_Email']</value>
      <webElementGuid>f2fa6388-7db9-47bf-8d46-1af0b9eedc84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appDetailsView']/div[4]/div[9]/input</value>
      <webElementGuid>1580ea5a-8d8f-4f74-b719-c4ed716deb69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[9]/input</value>
      <webElementGuid>a988a083-8642-4c4f-9545-636dd0cbd3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'leads_Email' and @name = 'leads.Email']</value>
      <webElementGuid>4d731883-b9f5-455e-b3d1-3ed72ebd8518</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
