<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2000 - 2009</name>
   <tag></tag>
   <elementGuidId>c69a6202-09d2-4482-a246-890d74e4ed23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.k-state-hover > a.k-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='2b71eeb4-9a75-412e-b85f-e2cd5b2c143d']/table/tbody/tr/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>74e6b177-bcc0-4a5a-9a84-e53034c9ea3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>db21b9b4-ab09-422c-b5b1-5bca5d3da38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link</value>
      <webElementGuid>871dafe9-e8f3-4cd3-8cd3-0fee939a70ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>7fd28efc-83d5-4d10-b178-9d41437b5105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>2000/0/1</value>
      <webElementGuid>a1fc1fbb-2b77-4f83-8f9f-52781a458c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2000 - 2009</value>
      <webElementGuid>b5b072f9-2d5b-47ce-94b4-fe5be0541dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2b71eeb4-9a75-412e-b85f-e2cd5b2c143d&quot;)/table[@class=&quot;k-content k-meta-view&quot;]/tbody[1]/tr[1]/td[@class=&quot;k-state-hover&quot;]/a[@class=&quot;k-link&quot;]</value>
      <webElementGuid>f4c70445-fe06-4be3-bba8-82b0fac6af3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2b71eeb4-9a75-412e-b85f-e2cd5b2c143d']/table/tbody/tr/td[2]/a</value>
      <webElementGuid>8e690755-7a60-465b-b660-e525f73b4e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2000 - 2009')]</value>
      <webElementGuid>9ab54c67-1ddd-4c27-aaba-04d58d048d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leadership Academy Lead (Day Shift)'])[1]/following::a[5]</value>
      <webElementGuid>9b987d11-d970-4514-b988-6cbfb1b0e951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Junior Recruitment Specialist'])[1]/following::a[5]</value>
      <webElementGuid>f046fe5c-1bff-404d-8b6f-cb9a0aaf8b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-Select Educational Attainment-'])[2]/preceding::a[11]</value>
      <webElementGuid>0cc9aa55-9787-4bcd-8cda-9c50f6b3bb55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='select'])[9]/preceding::a[11]</value>
      <webElementGuid>b2c294af-973e-4ab9-b548-0d24aae141d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2000 - 2009']/parent::*</value>
      <webElementGuid>9e6b5b80-6391-41ee-9e33-93b473cd8198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[8]</value>
      <webElementGuid>7903f1ea-340c-452d-9d29-b05bf20242e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>63cf7ae4-227b-49a2-b279-5e82a86f6798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '2000 - 2009' or . = '2000 - 2009')]</value>
      <webElementGuid>b26cfced-d289-450e-91ac-77639cd1f410</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
