<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2022</name>
   <tag></tag>
   <elementGuidId>7874c012-41ca-4e44-a54c-95768d0b41ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.k-link.k-nav-fast.k-state-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='179b3695-b5c3-4e3a-98f6-3dc46e898a81']/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5f3d3faa-cbf4-42e7-bf16-296de641af59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>77b1810a-115d-48c1-a4d2-91ab0189d589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6f590765-b7cc-4bc2-ab6e-9abd3d845440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>assertive</value>
      <webElementGuid>d7437f94-cec8-495f-af4e-2835beb12cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>00aeb0b1-9f50-431a-9620-bd3ce6de6558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link k-nav-fast k-state-hover</value>
      <webElementGuid>077ac28a-edc9-4d75-977c-906a97664896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>417129de-d320-47a8-9fd4-65152bd10609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2022</value>
      <webElementGuid>63219c27-6505-4b86-a348-58a46a0a7548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;179b3695-b5c3-4e3a-98f6-3dc46e898a81&quot;)/div[@class=&quot;k-header&quot;]/a[@class=&quot;k-link k-nav-fast k-state-hover&quot;]</value>
      <webElementGuid>48478a32-1e7b-4b6f-b651-3bd2d3645ff1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='179b3695-b5c3-4e3a-98f6-3dc46e898a81']/div/a[2]</value>
      <webElementGuid>abcc0cdd-f4ef-473b-99d0-f33704543d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2022')]</value>
      <webElementGuid>4cf2737b-1e0c-434e-a7cf-e1f0697c5e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leadership Academy Lead (Day Shift)'])[1]/following::a[2]</value>
      <webElementGuid>9084e366-03fd-4929-a80b-0c8027ae84f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Junior Recruitment Specialist'])[1]/following::a[2]</value>
      <webElementGuid>51feea75-3deb-4384-99c4-b08bb8ecdadc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-Select Educational Attainment-'])[2]/preceding::a[15]</value>
      <webElementGuid>16cd0df1-9cfb-475c-9ead-b7a41963099e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='select'])[9]/preceding::a[15]</value>
      <webElementGuid>d36436ef-e9ab-41e1-babc-0d31a661bf89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2022']/parent::*</value>
      <webElementGuid>e5f21798-e1a5-4c65-a56c-bdfb599bfabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>c4311339-32e5-495a-bc21-324fc55def25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a[2]</value>
      <webElementGuid>cc596241-0a96-4888-943a-38076002d71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '2022' or . = '2022')]</value>
      <webElementGuid>fc16cd62-3ba1-4903-b9dd-0fc030b589de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
