<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_July 2022</name>
   <tag></tag>
   <elementGuidId>6d8bbe8a-7d94-4506-affd-aff266026d65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.k-link.k-nav-fast.k-state-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='179b3695-b5c3-4e3a-98f6-3dc46e898a81']/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>35f049eb-c5ee-4911-8645-8c885affca05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f7201e8c-df9f-4e74-be3e-521d0c6cfefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>720e8f24-fd5d-48ff-ae31-89b7af723c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>assertive</value>
      <webElementGuid>84300396-1629-4087-9549-0f81c90019a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a181d89f-b2c4-484b-bb13-8647821f2d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link k-nav-fast k-state-hover</value>
      <webElementGuid>2ce7be6a-4987-4e06-b3f4-2a94deb01201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dbb34fd7-a9cc-47b3-bc06-1017e9a88250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>July 2022</value>
      <webElementGuid>e20de6d2-5e52-4fe2-869a-fb1142cd4aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;179b3695-b5c3-4e3a-98f6-3dc46e898a81&quot;)/div[@class=&quot;k-header&quot;]/a[@class=&quot;k-link k-nav-fast k-state-hover&quot;]</value>
      <webElementGuid>2dcf8b54-f710-443f-a072-3b7375c239db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='179b3695-b5c3-4e3a-98f6-3dc46e898a81']/div/a[2]</value>
      <webElementGuid>aac53d83-e46d-461f-99c3-7b8b5c432184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'July 2022')]</value>
      <webElementGuid>fe3b7f50-951e-4b26-99bb-538f388653c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leadership Academy Lead (Day Shift)'])[1]/following::a[2]</value>
      <webElementGuid>9e463035-4c1b-42bc-8f46-47f425b3e34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Junior Recruitment Specialist'])[1]/following::a[2]</value>
      <webElementGuid>0c970de3-214d-4562-9f9b-9c025f11c386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/preceding::a[2]</value>
      <webElementGuid>47b48e45-5e31-476b-bf8f-d68250a21b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mo'])[1]/preceding::a[2]</value>
      <webElementGuid>f6ce4d86-b807-41f2-951c-ed943f10e877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='July 2022']/parent::*</value>
      <webElementGuid>b42716ac-0d90-434b-b37d-9e6713fb6678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>8243a2eb-2d5a-4934-be35-cc2473f1696e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a[2]</value>
      <webElementGuid>85179034-8435-4479-9f6e-82e64e032218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'July 2022' or . = 'July 2022')]</value>
      <webElementGuid>43f9ade8-4961-4e84-8206-89a91284731c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
