<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit Application</name>
   <tag></tag>
   <elementGuidId>3a317cf2-b4b1-4685-a6e2-1cf2e6430c81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnShortFormRegister</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnShortFormRegister']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c78d6164-ccca-4f01-8a7d-6a6cc346c670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0c0a2ae4-c25a-4a37-a71e-2423c7f78c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-block btn-gradient</value>
      <webElementGuid>ba6165a6-aa23-4bff-b5b3-2d16cd5930bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnShortFormRegister</value>
      <webElementGuid>2cf02b4a-9267-4c37-9620-a8268e26e9db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>/qa-ropes-online/Applicants/Account/RegisterShortForm</value>
      <webElementGuid>5eaf9dea-e718-43cc-9dee-55f37af0d052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>doShortFormRegistration(this);</value>
      <webElementGuid>0b0b2e6b-1c6d-4a6f-b5a2-57262906332f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit Application</value>
      <webElementGuid>15da4c3c-4154-4cae-bcde-3b74ee226df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnShortFormRegister&quot;)</value>
      <webElementGuid>79f76d90-128d-4a24-a7c5-2e528f05ac88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnShortFormRegister']</value>
      <webElementGuid>7051f2b9-ddf6-4b15-b170-54e397c894bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='select'])[6]/following::button[1]</value>
      <webElementGuid>8dd05eda-f63b-4d95-8cf0-6d21a9f24b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bossjob'])[1]/following::button[1]</value>
      <webElementGuid>06a88bc7-d714-4919-a6f2-cfd2a1ad7c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registration via Activation Code'])[1]/preceding::button[1]</value>
      <webElementGuid>3cb2108c-0ba1-458d-8f30-bf5c85802dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>cdf54f3e-1964-44ec-b1b2-b1b3eb14af71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnShortFormRegister' and (text() = 'Submit Application' or . = 'Submit Application')]</value>
      <webElementGuid>ecf920d8-e99e-40ac-a316-bf40529265dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
