<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_select_a-i9dhlm6r6nn1</name>
   <tag></tag>
   <elementGuidId>78b9a4b1-6459-44be-ac39-ef03daf8c075</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-i9dhlm6r6nn1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-i9dhlm6r6nn1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ebd58b39-8fba-4a06-8e45-fa85b444c46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>74cedfb1-c959-4b51-9f8d-94ac3022e7bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Ld9GAMTAAAAAOYvz6cI9wF3lpbv5gzcX9n1QxKW&amp;co=aHR0cHM6Ly9jYXJlZXJzLXBoaWxpcHBpbmVzLjI0Ny1pbmMuY29tOjQ0Mw..&amp;hl=en&amp;v=CHIHFAf1bjFPOjwwi5Xa4cWR&amp;size=normal&amp;cb=e1kuqq65l431</value>
      <webElementGuid>5511ee7c-d82f-42cf-816b-0e6ca7d3a8f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>16e5ff47-ccc9-40cf-9d15-162e1f0e2b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>8a24708d-76f7-411f-b1c4-38f463b14d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>bd51d539-40a5-4f72-9aac-748473901ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-i9dhlm6r6nn1</value>
      <webElementGuid>09e6ec7e-8235-4a92-a3a3-1fa6e71f47b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8d864991-23dd-47b8-92d3-0cb954465fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>9768966c-1a09-42d2-b146-ef5a92a75d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>33db9bbd-0825-41ea-86c4-b76372103634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divRecaptcha&quot;)/div[@class=&quot;g-recaptcha g-transform&quot;]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>aeacf7f6-dc85-4ac3-9f07-5f95b916d17d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-i9dhlm6r6nn1']</value>
      <webElementGuid>ca2bbabe-1123-4b1f-be62-91c503eb4d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divRecaptcha']/div/div/div/iframe</value>
      <webElementGuid>d8535f95-ab2e-49b3-b8e6-d21f1f396588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>27f07869-1a92-4fbf-8427-e12ac66dd335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Ld9GAMTAAAAAOYvz6cI9wF3lpbv5gzcX9n1QxKW&amp;co=aHR0cHM6Ly9jYXJlZXJzLXBoaWxpcHBpbmVzLjI0Ny1pbmMuY29tOjQ0Mw..&amp;hl=en&amp;v=CHIHFAf1bjFPOjwwi5Xa4cWR&amp;size=normal&amp;cb=e1kuqq65l431' and @name = 'a-i9dhlm6r6nn1']</value>
      <webElementGuid>514e8cf0-9cc2-46a5-9260-2f107207e65a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
