<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_motorcycles_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>dad1319a-6853-4961-8f03-1e2249c99ed9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>94d3267a-32af-4527-b066-9c2fd56bf5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>ca6e76a7-14c7-47ab-b6cb-7d679bc31188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06ANYolquG-Z_BV-8uOY13gBrnmyQjuCNtzUYLEYCV9XdNRGc570CLb-YL3aWcTdQTzZl9SPHxkCNZ8wnNBFxi8oy-yk0FceMq92zRF8mxmUzpU5zW-uY8gnprFSA1qbCkVYqKnDVP09EStHrZJNC_fsajQVWxrJJPJwmNinbvYmxLhZ0E1DzX0cPBi7pjgxq-jR66CTasueQ4&amp;k=6Ld9GAMTAAAAAOYvz6cI9wF3lpbv5gzcX9n1QxKW</value>
      <webElementGuid>798faf38-3793-4cc7-b797-341eefb66721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>f16cf491-b988-4646-99c9-7e54cf5f87ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PostDeployment/SubmitAnApplication/AH_RopesOnline/Page_247 ROPES Online/iframe_Youtube_c-i9dhlm6r6nn1</value>
      <webElementGuid>33f05d0b-1f87-4aea-8de7-27a2785bd88c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>a52d55db-2395-4d57-8c1b-82be052cf21d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06ANYolquG-Z_BV-8uOY13gBrnmyQjuCNtzUYLEYCV9XdNRGc570CLb-YL3aWcTdQTzZl9SPHxkCNZ8wnNBFxi8oy-yk0FceMq92zRF8mxmUzpU5zW-uY8gnprFSA1qbCkVYqKnDVP09EStHrZJNC_fsajQVWxrJJPJwmNinbvYmxLhZ0E1DzX0cPBi7pjgxq-jR66CTasueQ4&amp;k=6Ld9GAMTAAAAAOYvz6cI9wF3lpbv5gzcX9n1QxKW')])[5]</value>
      <webElementGuid>cc599bdb-ddaf-4a98-8aea-1e18b324af54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>0852785c-ef50-4b6c-8a2e-195e3768797c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06ANYolquG-Z_BV-8uOY13gBrnmyQjuCNtzUYLEYCV9XdNRGc570CLb-YL3aWcTdQTzZl9SPHxkCNZ8wnNBFxi8oy-yk0FceMq92zRF8mxmUzpU5zW-uY8gnprFSA1qbCkVYqKnDVP09EStHrZJNC_fsajQVWxrJJPJwmNinbvYmxLhZ0E1DzX0cPBi7pjgxq-jR66CTasueQ4&amp;k=6Ld9GAMTAAAAAOYvz6cI9wF3lpbv5gzcX9n1QxKW']</value>
      <webElementGuid>d6e626d5-0f7e-49fb-bb8f-740a690b5ce4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
