<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_select_CompleteName.MiddleName</name>
   <tag></tag>
   <elementGuidId>296cb761-98b7-45d5-8bbd-6ede732579e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#middleName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='middleName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69096d10-6abe-40fa-b11a-056a04d39dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1205653b-a6a9-45fc-bbb2-17bd34ab6454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txtSFMiddleName text-box single-line</value>
      <webElementGuid>af8183ef-fea7-41c3-9be4-899c4a582124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>middleName</value>
      <webElementGuid>0a30aa4a-31f1-4208-804a-797fde7d8e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CompleteName.MiddleName</value>
      <webElementGuid>1aac56a8-ff86-47c0-8d66-8a41e78341c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Middle Name</value>
      <webElementGuid>56ee43c9-5834-4a7f-b12d-ac04b20d4a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d04cbb3-2535-4807-a847-734721999a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;middleName&quot;)</value>
      <webElementGuid>6aadf860-271b-440d-90f9-888221071082</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='middleName']</value>
      <webElementGuid>b873d605-0a3c-4273-8510-b2ae3d28444f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMiddleName']/input</value>
      <webElementGuid>08c8afd3-8fc1-41e0-82c8-a96d5f4d3b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>c3a26d29-97c6-4540-a30f-e800068ffdf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'middleName' and @name = 'CompleteName.MiddleName' and @placeholder = 'Middle Name' and @type = 'text']</value>
      <webElementGuid>b715f9e9-b0ee-4670-b018-b825aad51b63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
