<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PTRACK-DHP Recruiter Assignment and Statu_8de9f9</name>
   <tag></tag>
   <elementGuidId>be7fdd4a-2fd6-4af1-9659-ea5b8623461e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_lnkbtnPtrackDHPUploader</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder1_lnkbtnPtrackDHPUploader']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b1cf91ab-e909-4c69-b06a-f2750b205cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_lnkbtnPtrackDHPUploader</value>
      <webElementGuid>340b1014-ad9e-44bf-9090-e1ef5f541502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$ContentPlaceHolder1$lnkbtnPtrackDHPUploader','')</value>
      <webElementGuid>9307cb9f-3713-4dd3-9a8f-78ccd4dc5be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PTRACK-DHP Recruiter Assignment and Status Update Template</value>
      <webElementGuid>995710a6-7797-4825-9d2d-585058d69e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_lnkbtnPtrackDHPUploader&quot;)</value>
      <webElementGuid>50b03815-e55a-460a-a279-c80e443193e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_lnkbtnPtrackDHPUploader']</value>
      <webElementGuid>bb7e61a6-8c2c-41db-8d4a-85d8b887d064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/table[2]/tbody/tr/td/table/tbody/tr[14]/td[2]/a</value>
      <webElementGuid>5eb0653d-2d5f-4f34-b48e-781aa2cb94c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PTRACK-DHP Recruiter Assignment and Status Update Template')]</value>
      <webElementGuid>bf75d3d3-c130-433a-bdea-73a4556907e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BI'])[1]/following::a[1]</value>
      <webElementGuid>f49de5a9-30ca-4f34-8182-7e9ec7444303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pre-employment Requirements'])[1]/following::a[2]</value>
      <webElementGuid>38336a2b-e13d-4ac0-8834-0197d03b238b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DHP Leads Uploader Template'])[1]/preceding::a[1]</value>
      <webElementGuid>348c8338-3bde-4b0e-943c-b921c3ca56b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DHP Screener Assignment Template'])[1]/preceding::a[2]</value>
      <webElementGuid>e8211c35-25b7-4745-a4e1-61c6529c4c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PTRACK-DHP Recruiter Assignment and Status Update Template']/parent::*</value>
      <webElementGuid>c8a79633-678e-47ec-aebf-fdb595afd123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$ContentPlaceHolder1$lnkbtnPtrackDHPUploader','')&quot;)]</value>
      <webElementGuid>62bad2e5-d056-442f-9f0a-9ff1877176a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[14]/td[2]/a</value>
      <webElementGuid>b63365db-601a-4ebf-b906-2cb350913b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder1_lnkbtnPtrackDHPUploader' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$ContentPlaceHolder1$lnkbtnPtrackDHPUploader&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'PTRACK-DHP Recruiter Assignment and Status Update Template' or . = 'PTRACK-DHP Recruiter Assignment and Status Update Template')]</value>
      <webElementGuid>36f751a0-a6ad-4be4-9773-86b375366fef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
