<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next_1_2</name>
   <tag></tag>
   <elementGuidId>d746bf9f-3c4a-4414-bdf6-78782b0b8efd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dvInternetDetails > form > div.form-group.mt-3 > button.btn.btn-primary.btn-lg.float-end</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1ffc69ef-39d0-46c7-83e1-177831a32997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-lg float-end</value>
      <webElementGuid>fcbd9d0b-e79e-47ca-b90b-ecac4be8156b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>21529ff3-f981-4a28-8989-5670819c03c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
            Next
        </value>
      <webElementGuid>b0e7a494-3f60-4eaa-9129-336807d50303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dvInternetDetails&quot;)/form[1]/div[@class=&quot;form-group mt-3&quot;]/button[@class=&quot;btn btn-primary btn-lg float-end&quot;]</value>
      <webElementGuid>e10aae6a-6e42-4383-a1fe-33b03e5abffb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>c0ca8b62-f1bd-4f88-a04d-cff4dd5bee91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvInternetDetails']/form/div[2]/button</value>
      <webElementGuid>862bbc72-cae8-47a7-9501-2035539f5d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is your current UPLOAD speed as shown from the app/website?'])[1]/following::button[1]</value>
      <webElementGuid>8269a41d-a082-4011-b396-cb22cd012010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is your current DOWNLOAD speed as shown from the app/website?'])[1]/following::button[1]</value>
      <webElementGuid>e93dc19e-cc3c-431f-9534-cb7b31542767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload your speedtest here'])[1]/preceding::button[1]</value>
      <webElementGuid>5e99f8e1-5c90-4bab-8def-67cc265bb143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload your CV here'])[1]/preceding::button[1]</value>
      <webElementGuid>15652a54-7ddb-4895-897f-4868a66661ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>3ceadce6-0f6a-4a3d-83f3-46aecbb5f885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = ' 
            Next
        ' or . = ' 
            Next
        ')]</value>
      <webElementGuid>7e88bfcc-f46d-4c91-b0f2-f69bc05b4973</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
