<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Middle Name_MiddleName</name>
   <tag></tag>
   <elementGuidId>39ecae22-0998-4e6c-b84e-96443738c8a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MiddleName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MiddleName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37f7932c-7d44-4bf6-8eec-c36c30a6e75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-text form-control</value>
      <webElementGuid>74bc69cf-e369-4e9d-b61d-251f2a1fa967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e974eb50-cca4-4d3b-9896-6499cf698c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MiddleName</value>
      <webElementGuid>f02a5b9e-683e-4bb1-bdce-f02ae834263b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MiddleName</value>
      <webElementGuid>be611ace-10d6-4711-b31e-06f8bd44d413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MiddleName&quot;)</value>
      <webElementGuid>b8816d9f-61f4-421d-ada6-6c4751495b92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MiddleName']</value>
      <webElementGuid>4a416308-7edf-4978-aa84-270f1776159f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvPersonalInfo']/form/div[2]/div[2]/input</value>
      <webElementGuid>5f6fdcb7-13f4-45c6-8afa-3fd4533d5bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>18259d9c-2e6f-46da-a13b-5719251f6129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'MiddleName' and @name = 'MiddleName']</value>
      <webElementGuid>73a7a124-239f-45e9-922a-97eeb78d2240</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
