<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile Number(09xxxxxxxxx)_PrimaryMob_06cc24</name>
   <tag></tag>
   <elementGuidId>6f99198b-ca3e-436e-b2db-b78a3ecf7a48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PrimaryMobileNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PrimaryMobileNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e718c928-22d8-4434-b0cd-83263ea586ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-text form-control-sm</value>
      <webElementGuid>d19cc7d2-9695-4261-9a5b-799c037190f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>65269ccd-12ec-4ba3-8c2e-74458cc8853f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>94487937-5e97-4aec-8b57-fa34f31ed5d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>70ef1979-0063-481a-a433-ade0ce0886bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Not a valid phone number</value>
      <webElementGuid>81bf076c-3821-4f77-9150-c07a8fd714aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^\(?([0-9]{4})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$</value>
      <webElementGuid>83488120-411d-4b86-9bf5-6e90a68d64aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Mobile Number is required</value>
      <webElementGuid>609980be-8175-48f7-90a4-0f307d72d147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PrimaryMobileNumber</value>
      <webElementGuid>51b449fa-c2ec-4d2f-8041-e3b1bbdce9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PrimaryMobileNumber</value>
      <webElementGuid>5d198b9a-ef4f-4975-a17d-0ff175b138bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PrimaryMobileNumber&quot;)</value>
      <webElementGuid>2fad4e39-a905-4e49-8c17-fe8c370abcd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PrimaryMobileNumber']</value>
      <webElementGuid>43dfa648-d5aa-489f-9d0e-eb28793099da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvPersonalInfo']/form/div[3]/div[2]/input</value>
      <webElementGuid>185932bd-8b7d-42ae-b59f-a5b4c8c14df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>e7df0601-4d42-4b22-8727-553f03f8d9ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'PrimaryMobileNumber' and @name = 'PrimaryMobileNumber']</value>
      <webElementGuid>85979b0c-51d5-4187-9bb7-5ad1e1184bdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
