<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do you have your own Laptop or PC_HasLaptop</name>
   <tag></tag>
   <elementGuidId>07c39191-a701-4cd6-bfe1-49625f40017d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rdHasLaptop1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rdHasLaptop1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6bfae2dc-ed19-4689-b838-f6d64d1e0f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>c0fc4f4a-20c0-4846-bb9a-bb44b490fdea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>5ad8c3bc-54f0-4213-81ee-4f71266f851a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>20601c4e-c0c4-4ec4-b3b1-50186429ca65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdHasLaptop1</value>
      <webElementGuid>2373e271-6caa-424d-9e1c-5779c5b5a10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cb6f89dd-f01c-4342-b4a1-59ec7117256d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The HasLaptop field is required.</value>
      <webElementGuid>f3925fff-e8f6-4564-b83e-81e305618397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>HasLaptop</value>
      <webElementGuid>3d4809a9-215c-4607-bc6a-c823b7fe3a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdHasLaptop1&quot;)</value>
      <webElementGuid>666b2328-af1e-4fac-b082-f44f47d76772</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rdHasLaptop1']</value>
      <webElementGuid>8410e796-dbdf-453e-a9b9-f803d4cce8e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmApplicationDetails']/div[4]/div/div/input</value>
      <webElementGuid>a2f160f1-c5d1-43e2-ab23-35c8d559350d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>a91b1052-bc62-4333-a784-2e71777bc7ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'rdHasLaptop1' and @name = 'HasLaptop']</value>
      <webElementGuid>51036380-a71b-4f4f-9824-35ce03a51302</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
