<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FB Profile URL_FBProfileId</name>
   <tag></tag>
   <elementGuidId>98f337a4-0c44-439e-a05a-00ad10db055c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FBProfileId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FBProfileId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5414f341-a245-4d4a-bedd-553310d65a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-text form-control</value>
      <webElementGuid>1e078643-7f35-4572-b6f1-2cd8d7ac409d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4137a73c-6b54-4608-a1d6-235dcf612850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FBProfileId</value>
      <webElementGuid>e13c69aa-a8c1-4593-ad1a-af2cc6682e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FBProfileId</value>
      <webElementGuid>e9821c70-94f2-4861-9225-a6178a0c6d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FBProfileId&quot;)</value>
      <webElementGuid>f489a764-bbf3-4aaa-919a-76a75f8c4106</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FBProfileId']</value>
      <webElementGuid>f32ca56c-a7e1-479d-a7aa-04c3c110a442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvPersonalInfo']/form/div[5]/div[4]/input</value>
      <webElementGuid>f6fc1865-44f1-493d-b50d-046c4bf67a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>6a73fbeb-16e3-477b-aa1a-7ff01bbbee97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FBProfileId' and @name = 'FBProfileId']</value>
      <webElementGuid>886884f3-c5aa-41a3-8ac4-2d1b45e1e91c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
