<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_HasLaptop</name>
   <tag></tag>
   <elementGuidId>876e19c2-ce27-40a9-a50c-2b141952f9e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rdHasLaptop2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rdHasLaptop2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4fe773c9-6ba3-4614-8bcd-b913f8da4c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>fb1d6b94-952e-4edf-8bc4-d45e45160d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>0a2411cd-6bbd-4cd5-baa1-144b6942ce12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6cac5056-22b2-4ce2-8a36-7d907293251d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdHasLaptop2</value>
      <webElementGuid>331131d1-3252-421f-8f6a-0c84eb5160e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>38661066-b626-4ed2-8844-7278bd0bf75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>HasLaptop</value>
      <webElementGuid>226f2580-14c7-42c9-aa87-59ffd51ff313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdHasLaptop2&quot;)</value>
      <webElementGuid>0b28ab70-f74e-4544-992c-49ed7d54be65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rdHasLaptop2']</value>
      <webElementGuid>d12d80e2-90d9-4477-b8a5-4e315eb795d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmApplicationDetails']/div[4]/div/div[2]/input</value>
      <webElementGuid>19b79944-b183-44e8-b298-280f69f74adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/input</value>
      <webElementGuid>0536fa91-f7be-4052-887d-f14501a6889c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'rdHasLaptop2' and @checked = 'checked' and @name = 'HasLaptop']</value>
      <webElementGuid>d939a58e-cc39-4620-96ca-ce18d77e48ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
