<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_What is your current UPLOAD speed as _a1c1cb</name>
   <tag></tag>
   <elementGuidId>8834bce5-cfdc-415e-b63e-b4c9e7627d2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UploadSpeed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UploadSpeed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e31a2113-1607-4203-a8a3-981b6925d69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-text form-control-sm</value>
      <webElementGuid>658aeb30-1c45-4a2b-9fd2-86969be28fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30acaa32-0344-4203-a6da-09e20ccdf0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UploadSpeed</value>
      <webElementGuid>282150af-6270-468a-8819-9b5e60900057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UploadSpeed</value>
      <webElementGuid>a20723af-62af-436f-9b6a-45cb3c72c818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UploadSpeed&quot;)</value>
      <webElementGuid>609094ba-575c-480e-83ab-99d0c630ac02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UploadSpeed']</value>
      <webElementGuid>1f3e13cf-356d-4a59-88b0-89c957dc2a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvInternetDetails']/form/div/div[2]/input</value>
      <webElementGuid>91909d3c-3a4c-49bd-9b5d-1f7304cbba77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/form/div/div[2]/input</value>
      <webElementGuid>37c13942-a211-4d6f-b5d7-a497b10c0002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'UploadSpeed' and @name = 'UploadSpeed']</value>
      <webElementGuid>2b37e97d-0afc-4d1f-85c4-77324efcd38a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
