<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_What is your current UPLOAD speed as _a1c1cb</name>
   <tag></tag>
   <elementGuidId>3843c243-5309-415e-87e8-0a81d36392e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UploadSpeed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UploadSpeed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3258167f-121d-45da-826f-0841b6c82800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-text form-control-sm</value>
      <webElementGuid>4a8cce4b-c2ad-4488-b6a4-7c7c634bddaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>29f63bcd-c59a-43d6-94b0-222ea49d2417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UploadSpeed</value>
      <webElementGuid>a1f94ed3-90ee-4381-8202-24431c08a756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UploadSpeed</value>
      <webElementGuid>6c44212b-6b92-409d-b51a-04b4624ef2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UploadSpeed&quot;)</value>
      <webElementGuid>3fd876f0-4186-4c7a-b292-441dedd30980</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UploadSpeed']</value>
      <webElementGuid>c2978d0a-1309-44ef-ab88-957b1d6ed1dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvInternetDetails']/form/div/div[2]/input</value>
      <webElementGuid>e4e05282-c679-48a7-84a0-6288b185fdd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/form/div/div[2]/input</value>
      <webElementGuid>e3a21c15-c69d-40f9-90bc-6efab5f2467d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'UploadSpeed' and @name = 'UploadSpeed']</value>
      <webElementGuid>132b5c6e-f420-48ad-a7f0-c5083acea804</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
