<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Are you willing to work in shifting s_867183</name>
   <tag></tag>
   <elementGuidId>472ff529-e4c4-420a-a3b7-7c6242f46658</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rdIsWillingShifting1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rdIsWillingShifting1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8949fee-ab28-4aef-92d7-145ecb5af998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>716d2a32-899a-41f8-93a5-1d503b778c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>3ddd06b5-6e6e-4b4a-9ded-b9947ac9f18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d18dedeb-44cd-4274-81de-980c14206cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdIsWillingShifting1</value>
      <webElementGuid>07081f34-c1e7-4ec8-9a58-09b6045cfbca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>547ffa07-dfc7-4826-966d-d4219f76484a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The IsWillingShifting field is required.</value>
      <webElementGuid>fef77907-2a2f-4287-9774-ad0a2ebe9b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsWillingShifting</value>
      <webElementGuid>7f540d7c-4f2d-4386-aca5-28c687e966fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdIsWillingShifting1&quot;)</value>
      <webElementGuid>687bdf51-5763-4349-897f-2bc353fc8de0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rdIsWillingShifting1']</value>
      <webElementGuid>8b1f48d6-97a4-41fd-af1b-fcb566d4ffa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmApplicationDetails']/div[5]/div/div/input</value>
      <webElementGuid>afd934e7-aeae-4fa3-bd13-e2f6102ae120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>64f75834-e774-48e5-afe0-46568f28cebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'rdIsWillingShifting1' and @name = 'IsWillingShifting']</value>
      <webElementGuid>db939daf-f95a-4270-8c90-09b6f2e5708c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
