<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do you have your own Laptop or PC_HasLaptop</name>
   <tag></tag>
   <elementGuidId>3fa00ef6-1311-47bd-b834-14c16edfe432</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rdHasLaptop1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rdHasLaptop1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd23c790-35f5-45c8-b8a3-42adf4665864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>09477a09-85c9-470a-b4da-61bc3762f5b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>3f74042e-52b0-4d5d-8ab5-9d14fe5a5172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>08dbea8e-28d6-416b-be7e-a4c705ed2977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdHasLaptop1</value>
      <webElementGuid>51963fa0-8788-41eb-9b40-d76b85e066bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>717e5af8-09de-4ffe-975e-66527a85d444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The HasLaptop field is required.</value>
      <webElementGuid>fde4c6e2-3f5c-43e4-8a8d-74da68a41f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>HasLaptop</value>
      <webElementGuid>638d566e-0814-4749-9799-5e52e070f369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdHasLaptop1&quot;)</value>
      <webElementGuid>a01cc178-f03e-4412-a063-947559397154</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rdHasLaptop1']</value>
      <webElementGuid>b048f2aa-fbb6-43d9-a2df-38b343c10889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmApplicationDetails']/div[4]/div/div/input</value>
      <webElementGuid>a8935350-a7ec-48b8-84ea-f04791bc3383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>d99f659f-12f4-4114-91b1-41d67bc5d8f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'rdHasLaptop1' and @name = 'HasLaptop']</value>
      <webElementGuid>9fbc097e-8e31-4320-a59d-b67662f31043</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
