<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_What is your current DOWNLOAD speed a_0f08af</name>
   <tag></tag>
   <elementGuidId>b1add7d5-8424-4298-9bd9-8de31a03b06d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DownloadSpeed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DownloadSpeed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dbc8f396-be2a-4366-9970-fe11d08ae75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-text form-control-sm</value>
      <webElementGuid>c725df92-4a2e-4f7b-93c2-0f89d073d68e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d3dbe0b2-0ed2-4876-b0e5-2c2a878c5f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DownloadSpeed</value>
      <webElementGuid>1f7e6de8-e56d-4e13-a9a3-c661831b4e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DownloadSpeed</value>
      <webElementGuid>1b195039-97f3-4680-aefc-89e0bef8a49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DownloadSpeed&quot;)</value>
      <webElementGuid>073d96ba-752c-48c2-83c0-53c5504edee9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DownloadSpeed']</value>
      <webElementGuid>8796c819-1891-439b-8f8f-c88621bf50cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvInternetDetails']/form/div/div/input</value>
      <webElementGuid>a14ecccb-5775-422a-b874-318685af8279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/form/div/div/input</value>
      <webElementGuid>b940bf79-6cec-461c-b39e-b7a1c56fa4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'DownloadSpeed' and @name = 'DownloadSpeed']</value>
      <webElementGuid>873867b3-f7da-4b50-a00d-f01d0e0b89c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
