<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Are you willing to work in shifting s_867183</name>
   <tag></tag>
   <elementGuidId>2318aa86-1584-46a5-9b1d-b44bf7875c52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rdIsWillingShifting1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rdIsWillingShifting1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7acdbd01-bbf9-4d4c-91aa-e020c922f3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>1ad6623b-dda1-44c0-8dbf-bcc953d12113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>09965eee-5f16-493b-8ae0-4047f2a86506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9eb6ea37-a0f7-4fef-8afe-607eed22ca4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdIsWillingShifting1</value>
      <webElementGuid>41918496-f331-4fe1-b9da-ab1c88d24768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>24c08c20-f240-433f-a67e-0a5976302765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The IsWillingShifting field is required.</value>
      <webElementGuid>fc7e0795-3ab6-4d70-8cbb-80440154d4b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsWillingShifting</value>
      <webElementGuid>da7f66bd-b4b0-483a-ba7d-ba5446ea2803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdIsWillingShifting1&quot;)</value>
      <webElementGuid>78421d76-c80f-4c56-b547-2d521e06dfc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rdIsWillingShifting1']</value>
      <webElementGuid>c58a7a24-77ed-4e10-85de-2b4d95b7b50f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmApplicationDetails']/div[5]/div/div/input</value>
      <webElementGuid>845d6f1d-7afe-409c-9172-7a6c560a25ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>beb1f0e0-a2b5-4ece-b2d2-cc6362da3634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'rdIsWillingShifting1' and @name = 'IsWillingShifting']</value>
      <webElementGuid>5e59a1f1-0ba6-4bea-851e-cbf3b9aeaf3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
