<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select SiteOrtigasCyber SigmaPampang_717d2b</name>
   <tag></tag>
   <elementGuidId>e7d0747d-a4eb-4ce0-bf56-b2769deab7a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#JobPreference_Site</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='JobPreference_Site']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7ebff8b5-ac7e-4997-8626-d35041aa45ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select form-text form-select-sm</value>
      <webElementGuid>1dd88627-0179-48c5-b874-34db489d92a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4ab7a964-67a0-420f-9a9a-621467005219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Please select your preferred work location</value>
      <webElementGuid>ad08c9c2-7ffb-4a0e-bb0f-f6f874c2b2c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>JobPreference_Site</value>
      <webElementGuid>18b43f43-a8bf-4224-bc9b-f633fc5bfb5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>JobPreference_Site</value>
      <webElementGuid>1a8697a2-14df-4e42-9663-f8d97866f77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Site
Ortigas
Cyber Sigma
Pampanga
Cybergate
</value>
      <webElementGuid>009bd22c-e9d4-4fde-a9cd-c3e3f14b8062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JobPreference_Site&quot;)</value>
      <webElementGuid>81b58010-24be-4860-bbf9-936487cf22b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='JobPreference_Site']</value>
      <webElementGuid>116b90e1-5ac7-4669-b10b-b839f16ef015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmApplicationDetails']/div[2]/select</value>
      <webElementGuid>cc0e1d6c-433a-4206-bc71-a8a35a38b2d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Where is your preferred work location?'])[1]/following::select[1]</value>
      <webElementGuid>cf93a725-293c-49cd-9f93-bc91557a5971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How many months/years of BPO Experience do you have?'])[1]/following::select[2]</value>
      <webElementGuid>434a5ac4-65e9-4c89-ba12-f1509752f6d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you have your own Laptop or PC ?'])[1]/preceding::select[2]</value>
      <webElementGuid>62f60369-d3f1-47ca-982f-11db31219a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::select[2]</value>
      <webElementGuid>59bc2be7-9d67-461f-b96b-62a737d233c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/select</value>
      <webElementGuid>f77aeb07-a2f4-4e79-9730-8db0660e0403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'JobPreference_Site' and @name = 'JobPreference_Site' and (text() = 'Select Site
Ortigas
Cyber Sigma
Pampanga
Cybergate
' or . = 'Select Site
Ortigas
Cyber Sigma
Pampanga
Cybergate
')]</value>
      <webElementGuid>3c6e64ee-de18-4db0-8640-87f36eb2b297</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
