<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_select_Contact.MobileNumber</name>
   <tag></tag>
   <elementGuidId>9eb23eb0-01d8-4956-b752-4537e5a1e036</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtShortFormMobile']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;txtShortFormMobile&quot;)[count(. | //input[@class = 'form-control txtShortFormMobile' and @id = 'txtShortFormMobile']) = count(//input[@class = 'form-control txtShortFormMobile' and @id = 'txtShortFormMobile'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtShortFormMobile</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59624071-c1d9-481b-980e-ad6bd6ae8d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txtShortFormMobile</value>
      <webElementGuid>6644a61e-d86f-417c-ba20-cb748222799c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtShortFormMobile</value>
      <webElementGuid>5e651d2d-ebf7-419c-b0b7-f8e16104269c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Contact.MobileNumber</value>
      <webElementGuid>5a65ba8c-a92d-4773-894c-0928e0c0e2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contact No.</value>
      <webElementGuid>3e887422-7eb4-4b7b-864f-9412d0a65db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>maskedtextbox</value>
      <webElementGuid>acbdbf2c-3283-4982-b5c0-d55b56008de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6ec0a18a-4c46-435f-8de4-d38113f25c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtShortFormMobile&quot;)</value>
      <webElementGuid>8a0a090f-45c1-413a-9b63-ee9b0092bd1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtShortFormMobile']</value>
      <webElementGuid>c75d889d-082c-4f12-8feb-1d2714c5a32d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMobileNumber']/input</value>
      <webElementGuid>a2048619-fc2d-4c60-80f9-2a2146873111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>9555acdf-57c1-43b7-aeba-21b8c8afda84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtShortFormMobile' and @name = 'Contact.MobileNumber' and @placeholder = 'Contact No.']</value>
      <webElementGuid>51511011-a7b7-49d2-a2ba-de206ca80d59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
