<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Is Active_dvCBMG_UserGroupsbtnEdit</name>
   <tag></tag>
   <elementGuidId>5ecdc1e9-8e4a-451a-a67d-1f7d6b5802dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dvCBMG_UserGroups_btnEdit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dvCBMG_UserGroups_btnEdit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e9f45ca-6474-49d4-8ffb-d2a16ac96d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>523dcf03-70a1-479c-b8dc-bb4d6ac99e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dvCBMG_UserGroups$btnEdit</value>
      <webElementGuid>702fd8d5-bb0a-406e-b0fc-fdbcce48bdf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>871d6827-e5e7-4d11-a471-3430dce74bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dvCBMG_UserGroups_btnEdit</value>
      <webElementGuid>77bad6c3-77cd-4178-92a2-3f811f0b593d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eb00ff06-b88b-4672-bf9d-b2be4b1c7d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dvCBMG_UserGroups_btnEdit&quot;)</value>
      <webElementGuid>a12afdba-caf5-4705-841b-9d63d0210876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PostDeployment/ScreenerMaintenance/Set_Inactive_Screener/Page_247 IRIS - Table Administration/iframe_Table Title_ctl00_ContentPlaceHolder_3b72f3</value>
      <webElementGuid>1f0ba418-76f8-4df0-b831-16a9a3f03d6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dvCBMG_UserGroups_btnEdit']</value>
      <webElementGuid>cd158967-6a80-4264-a1c0-d4610b8cd5a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dvCBMG_UserGroups']/tbody/tr[6]/td/input</value>
      <webElementGuid>9cc8ff63-6260-49c6-ba27-d5e254f05b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>c5fbcd80-585d-44e1-9127-cdeac16cccda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'dvCBMG_UserGroups$btnEdit' and @id = 'dvCBMG_UserGroups_btnEdit']</value>
      <webElementGuid>ec189fe1-188b-44d1-bf22-61b1fa6f9edd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
