<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Is Active_dvCBMG_UserGroupsbtnUpdate</name>
   <tag></tag>
   <elementGuidId>56872784-8758-4e66-9f1c-ce2a2ff36047</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dvCBMG_UserGroups_btnUpdate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dvCBMG_UserGroups_btnUpdate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0a5356c-8202-40ef-9cb3-5f54a23cf089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>29d1cbc8-c794-453d-9ff4-dc9e7017bc8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dvCBMG_UserGroups$btnUpdate</value>
      <webElementGuid>78e134a8-9120-45f5-820d-99e5b5cf7a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Update</value>
      <webElementGuid>053022d3-27a5-475d-86ce-2c5a4e489ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dvCBMG_UserGroups_btnUpdate</value>
      <webElementGuid>daaf0140-6909-4dea-823c-dea56e38a69c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>33bb6986-1746-41d1-96b7-ba023de24780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dvCBMG_UserGroups_btnUpdate&quot;)</value>
      <webElementGuid>e13ac65a-d3e5-4237-915e-3aa68272b881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PostDeployment/ScreenerMaintenance/Set_Inactive_Screener/Page_247 IRIS - Table Administration/iframe_Table Title_ctl00_ContentPlaceHolder_3b72f3</value>
      <webElementGuid>78d326c6-bcfe-466e-ba33-11a8ec252ebf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dvCBMG_UserGroups_btnUpdate']</value>
      <webElementGuid>4bb4361a-857f-4315-9817-25d79d471d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dvCBMG_UserGroups']/tbody/tr[6]/td/input</value>
      <webElementGuid>ef649ea6-8b29-4fdd-a08f-f02f3741fe37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>fc33baa7-6d64-4b6f-b012-a88cf438ffb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'dvCBMG_UserGroups$btnUpdate' and @id = 'dvCBMG_UserGroups_btnUpdate']</value>
      <webElementGuid>948843c7-6ae5-4841-9a99-c80971d7a1cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
