<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City Of Residence_leads.CityOfResidence</name>
   <tag></tag>
   <elementGuidId>3ea240d8-b733-4338-95c7-8823cf356698</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leads_CityOfResidence']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#leads_CityOfResidence</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a44b01e1-ac52-4cfc-b78f-ca60c276eb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-text form-control-sm</value>
      <webElementGuid>47e39585-405b-4774-ba39-e34d8d573509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a0f525c1-3fb9-4514-bfb2-829e48b7cddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leads_CityOfResidence</value>
      <webElementGuid>d8f67146-3a7a-42ca-9c2a-275e18692bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leads.CityOfResidence</value>
      <webElementGuid>80914cd2-ad5a-412a-8aed-5f0cd5cec6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leads_CityOfResidence&quot;)</value>
      <webElementGuid>23ec052f-5001-43e7-a264-ba402797dcea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leads_CityOfResidence']</value>
      <webElementGuid>e16ccf1d-f33f-41be-ad44-529614adc63a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appDetailsView']/div[4]/div[18]/input</value>
      <webElementGuid>02c0b602-ef57-4912-b6f9-edaed9b95c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[18]/input</value>
      <webElementGuid>04766c9a-804c-4bb5-9421-790e051293b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'leads_CityOfResidence' and @name = 'leads.CityOfResidence']</value>
      <webElementGuid>60059ed1-197c-4803-8a65-05db6474295c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
