<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_listAttributesdate_of_birth01031989equi_caf24a</name>
   <tag></tag>
   <elementGuidId>05c2f601-26bf-4070-9eff-db8833c3668c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Recruiter', &quot;'&quot;, 's Notes Instruction')])[1]/following::div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = concat('listAttributesdate_of_birth01/03/1989equipmentYesgeo_cityPasay Cityhighest_qualification_levelBachelor' , &quot;'&quot; , 's Degreeindustry_experience> 6 months to 1 yearinternet_download_speed>= 10mbpsinternet_typeFixed Lineinternet_upload_speed>= 5mbpslegal_working_ageYesmiddle_initialOmiddle_nameAnight_shift_flexibiltyYesposition_applied_forCustomer Retail Representativepreferred_cityMakatipreferred_work_locationYessales_experienceYes - BPOsecondary_contact_number926 987 8081sourceOnline - Jobyodawilling_to_work_on_siteYeswillingess_to_travel_mecqNo') or . = concat('listAttributesdate_of_birth01/03/1989equipmentYesgeo_cityPasay Cityhighest_qualification_levelBachelor' , &quot;'&quot; , 's Degreeindustry_experience> 6 months to 1 yearinternet_download_speed>= 10mbpsinternet_typeFixed Lineinternet_upload_speed>= 5mbpslegal_working_ageYesmiddle_initialOmiddle_nameAnight_shift_flexibiltyYesposition_applied_forCustomer Retail Representativepreferred_cityMakatipreferred_work_locationYessales_experienceYes - BPOsecondary_contact_number926 987 8081sourceOnline - Jobyodawilling_to_work_on_siteYeswillingess_to_travel_mecqNo'))]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>container</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>listAttributesdate_of_birth01/03/1989equipmentYesgeo_cityPasay Cityhighest_qualification_levelBachelor's Degreeindustry_experience> 6 months to 1 yearinternet_download_speed>= 10mbpsinternet_typeFixed Lineinternet_upload_speed>= 5mbpslegal_working_ageYesmiddle_initialOmiddle_nameAnight_shift_flexibiltyYesposition_applied_forCustomer Retail Representativepreferred_cityMakatipreferred_work_locationYessales_experienceYes - BPOsecondary_contact_number926 987 8081sourceOnline - Jobyodawilling_to_work_on_siteYeswillingess_to_travel_mecqNo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-dhp-layout[1]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;dhp-layout&quot;]/app-application-view[1]/main[1]/application-form[1]/applicant-details[1]/div[@class=&quot;parent-container&quot;]/aside[@class=&quot;toggled&quot;]/app-attributes[1]/div[@class=&quot;container&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Recruiter', &quot;'&quot;, 's Notes Instruction')])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send ROPES Credentials'])[1]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-attributes/div</value>
   </webElementXpaths>
</WebElementEntity>
