<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Filter</name>
   <tag></tag>
   <elementGuidId>fe2f5a05-d350-437f-a145-6b6748c17637</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnFilter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnFilter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ec437b25-dcaa-4a9f-9332-42821b68bd27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnFilter</value>
      <webElementGuid>f9868da7-ffea-419d-bc09-0dd27cf8520b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9eb71b27-c050-4f3a-9350-14b0e1ba7c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm</value>
      <webElementGuid>b2ebec47-cca1-4da3-b93c-50d5938c4d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                         Filter
                    </value>
      <webElementGuid>9c9e4194-c67d-4642-b814-37ff91fc3d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnFilter&quot;)</value>
      <webElementGuid>e31545ff-19c5-4e1a-bd65-5ce308eaf91f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnFilter']</value>
      <webElementGuid>5f3d72e2-ba5b-4784-9bcb-71cd235933cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmFilterRecipients']/div/div/div[10]/div/button</value>
      <webElementGuid>f986e569-2e53-46e6-9be0-bcdaba3d96a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incomplete applications'])[1]/following::button[1]</value>
      <webElementGuid>a9050203-5120-4f48-8dd0-64a54aee095b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ask a question only'])[1]/following::button[1]</value>
      <webElementGuid>06e0ee9c-cb2d-45dd-9cd2-2cb618dd3b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Filter']/parent::*</value>
      <webElementGuid>7dc10566-fca3-4ec5-9c81-b970d493700f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/button</value>
      <webElementGuid>20067b34-4020-4ba7-9314-0027eae8c40f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnFilter' and @type = 'submit' and (text() = '
                         Filter
                    ' or . = '
                         Filter
                    ')]</value>
      <webElementGuid>fe12fb47-aec0-473a-a01e-2acfc5de65b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
