<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit Application</name>
   <tag></tag>
   <elementGuidId>65d7ba15-1e47-43ed-accf-120c06e809ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnShortFormRegister</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnShortFormRegister']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0baa428e-711f-4de7-84c2-590d23bc1b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1aac65dc-7133-47ef-94c9-4b1ff7527343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-block btn-gradient</value>
      <webElementGuid>b78cfdfc-5845-4947-8c03-83235c1bd60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnShortFormRegister</value>
      <webElementGuid>bb589454-f99e-4780-a78a-1535752fea31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>/qa-ropes-online/Applicants/Account/RegisterShortForm</value>
      <webElementGuid>f8a333fb-cee8-4d66-933c-c64baea958c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>doShortFormRegistration(this);</value>
      <webElementGuid>f41c7e0d-21a7-4141-bfb9-1ad09d02ecf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit Application</value>
      <webElementGuid>3224b4ba-506c-4002-bf13-0b5c3c517c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnShortFormRegister&quot;)</value>
      <webElementGuid>421c8aa3-d8b6-49ef-9e53-64f2fc9f568d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnShortFormRegister']</value>
      <webElementGuid>890c5530-e08b-4f5a-b78d-b8f7caf596fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='select'])[6]/following::button[1]</value>
      <webElementGuid>47357e12-aab9-4dc6-b9c9-96854e533548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flyers'])[1]/following::button[1]</value>
      <webElementGuid>864fb6b1-1b9e-421b-a3a4-b911eb0daa8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registration via Activation Code'])[1]/preceding::button[1]</value>
      <webElementGuid>6224c4ee-3363-45e2-83ae-629b74af4309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>4d719d03-74dc-4084-ae8d-8a8b04be1995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnShortFormRegister' and (text() = 'Submit Application' or . = 'Submit Application')]</value>
      <webElementGuid>9e89f5bd-8569-4526-9979-5e5cbf0c2ec3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
