<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_select_a-6nj108r52esm</name>
   <tag></tag>
   <elementGuidId>c2b1e8c0-a772-4673-a18a-2d01b34d999f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-6nj108r52esm&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-6nj108r52esm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>53d715d5-6794-4f5f-ac80-af20d7a97a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>30250888-e3b7-47ce-872d-580149545440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Ld9GAMTAAAAAOYvz6cI9wF3lpbv5gzcX9n1QxKW&amp;co=aHR0cHM6Ly9jYXJlZXJzLXBoaWxpcHBpbmVzLjI0Ny1pbmMuY29tOjQ0Mw..&amp;hl=en&amp;v=gWN_U6xTIPevg0vuq7g1hct0&amp;size=normal&amp;cb=c5606sy2t0tp</value>
      <webElementGuid>f5a4d7e0-a77e-4963-8050-4da178926e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>750a9ef1-4abb-4cd1-b4a9-d79956d5c697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>cfa3d070-c208-4652-8ad1-5cb32caf1301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>343abf15-94a3-4454-ac8d-4ce5966d2d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-6nj108r52esm</value>
      <webElementGuid>8071e1a3-5d0a-4d88-8d90-7639af5324f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>322d5aeb-263f-4f4d-a9a0-4df3de066044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>6a94e71a-383c-492e-b7dc-6d3422723633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>7cc33d5c-f6a4-47c7-b4d3-d2bf46bb592c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divRecaptcha&quot;)/div[@class=&quot;g-recaptcha g-transform&quot;]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>c0b59fb2-93c6-4096-a918-c5834d504f99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-6nj108r52esm']</value>
      <webElementGuid>0e34c1f0-2e21-4bb3-8ba9-dc6461fa4c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divRecaptcha']/div/div/div/iframe</value>
      <webElementGuid>298513c1-48f3-4d27-a861-01fcf8dae145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c0125ebc-de5a-4cdb-93b2-28bc6ffe34e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Ld9GAMTAAAAAOYvz6cI9wF3lpbv5gzcX9n1QxKW&amp;co=aHR0cHM6Ly9jYXJlZXJzLXBoaWxpcHBpbmVzLjI0Ny1pbmMuY29tOjQ0Mw..&amp;hl=en&amp;v=gWN_U6xTIPevg0vuq7g1hct0&amp;size=normal&amp;cb=c5606sy2t0tp' and @name = 'a-6nj108r52esm']</value>
      <webElementGuid>77a9b204-92e2-44a6-b507-2e992f29ab6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
