<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_select_CompleteName.MiddleName</name>
   <tag></tag>
   <elementGuidId>644b8e5b-aa9e-45fd-b28a-88d908848c5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#middleName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='middleName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1e18553-4e75-4c10-9b8d-eb019bc51d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>de089cfd-c51b-4aa8-a5ba-852956f0d8a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txtSFMiddleName text-box single-line</value>
      <webElementGuid>6a80fc1f-be8d-4296-833c-e3ab4c1271bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>middleName</value>
      <webElementGuid>35cf5628-e2c5-421b-b1d8-9e784ff101b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CompleteName.MiddleName</value>
      <webElementGuid>58d2c4f4-f6e4-4590-a956-cd9e4b1b4836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Middle Name</value>
      <webElementGuid>12f28ec0-444a-4abb-be5c-87ae9921f41b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a17f3262-005a-4f08-bf63-5e548675da29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;middleName&quot;)</value>
      <webElementGuid>a52f50ba-288c-4449-bde4-7af9c3fbeead</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='middleName']</value>
      <webElementGuid>34318c6a-2801-4f0e-9caf-53cfbae413ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMiddleName']/input</value>
      <webElementGuid>5915c10e-4449-4c2e-9e10-0e7fde38f768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>e8431ac6-3826-402b-8efc-4f790a1936be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'middleName' and @name = 'CompleteName.MiddleName' and @placeholder = 'Middle Name' and @type = 'text']</value>
      <webElementGuid>dc820e95-9192-497e-a9e3-4ab1ad10ca17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
