<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Table Administration</name>
   <tag></tag>
   <elementGuidId>84ca0110-eae7-40d4-8908-5560e82e96d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_TreeViewMainMenut34']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_TreeViewMainMenut34</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d80be380-b380-4587-b700-042d3a1b7532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ctl00_TreeViewMainMenu_0</value>
      <webElementGuid>9b282701-1af6-43e1-a66a-cb7ed059d718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/webportal/MemberPages/CBMG/CBMG_Tables/TableAdminMain.aspx</value>
      <webElementGuid>490b3d4e-8f82-44ee-a8ff-3728127dc9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Table Administration</value>
      <webElementGuid>b59ad479-04a8-4299-a0f9-e56150e2f0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_TreeViewMainMenut34</value>
      <webElementGuid>60909187-0dcc-4b51-9956-f150d9975042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Table Administration</value>
      <webElementGuid>3bb9efa1-318f-495f-a409-d7eba217f27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_TreeViewMainMenut34&quot;)</value>
      <webElementGuid>f8b56588-8d28-48b4-b6c9-41dd06fb19c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_TreeViewMainMenut34']</value>
      <webElementGuid>88f08608-eabd-48f4-9b2f-c8aef6d1a41f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_TreeViewMainMenun0Nodes']/table[9]/tbody/tr/td[4]/a</value>
      <webElementGuid>a13025a5-5f7a-479c-93d3-52da70650bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Table Administration')]</value>
      <webElementGuid>f6ec44a8-dd20-4da5-9919-ccf5d340e55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ropes Report Last 3 days'])[1]/following::a[2]</value>
      <webElementGuid>27febe54-f120-430b-89e7-c42b25a6e406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ropes Report'])[1]/following::a[4]</value>
      <webElementGuid>8f5208e0-0d3a-42ac-bfde-d8f2fdb1e2bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROPES BOSS'])[1]/preceding::a[2]</value>
      <webElementGuid>ac001e66-7c9c-492a-9c6b-92b0cb036de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave Employee Package Tool'])[1]/preceding::a[6]</value>
      <webElementGuid>aab71b29-6305-4ef2-b64d-e4574f0a2f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Table Administration']/parent::*</value>
      <webElementGuid>4bec45f6-6367-4e6e-9c60-5c0eabbfdb01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/webportal/MemberPages/CBMG/CBMG_Tables/TableAdminMain.aspx')])[2]</value>
      <webElementGuid>d9609a38-5838-4e12-acfd-7a51964f7ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[9]/tbody/tr/td[4]/a</value>
      <webElementGuid>b59c5d08-bff7-4ebe-9664-cb182a768824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/webportal/MemberPages/CBMG/CBMG_Tables/TableAdminMain.aspx' and @title = 'Table Administration' and @id = 'ctl00_TreeViewMainMenut34' and (text() = 'Table Administration' or . = 'Table Administration')]</value>
      <webElementGuid>f2f7ac88-f732-429f-b5a6-19a5346a469f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
