<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>22244adc-c427-4db3-ba15-b735b1dc6cd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='gvCBMG_UserGroups']/tbody/tr[52]/td/table/tbody/tr/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ce39cdcd-74bd-4252-91e1-265708c05a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('gvCBMG_UserGroups','Page$2')</value>
      <webElementGuid>17411e4d-c940-4179-9f3c-cfc865e4b797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ddb5a82d-e49d-493b-b853-12c1abbece08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvCBMG_UserGroups&quot;)/tbody[1]/tr[@class=&quot;gridviewpager&quot;]/td[1]/table[1]/tbody[1]/tr[1]/td[2]/a[1]</value>
      <webElementGuid>07998c05-3294-4e57-833e-dda08d60a799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PostDeployment/ScreenerMaintenance/Set_Screener/Page_247 IRIS - Table Administration/iframe_Table Title_ctl00_ContentPlaceHolder_3b72f3</value>
      <webElementGuid>21f44b35-fefb-4db6-a348-0fba4643f297</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvCBMG_UserGroups']/tbody/tr[52]/td/table/tbody/tr/td[2]/a</value>
      <webElementGuid>c37abc42-1c10-4d20-9972-a7e88d451503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2')]</value>
      <webElementGuid>17063f9f-ee68-4e33-9f7f-aa6ab86efa40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recruiter'])[27]/following::a[1]</value>
      <webElementGuid>87bad348-1c4d-4d7a-a326-67697477c3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estrada, Eric P.'])[1]/following::a[1]</value>
      <webElementGuid>92c4ecb1-7c38-4f13-b353-4cc1514719bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('gvCBMG_UserGroups','Page$2')&quot;)]</value>
      <webElementGuid>c6a98039-cd01-44e7-98dd-259f877432dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>7d370b17-e63e-4768-9005-ed5b2a6951ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;gvCBMG_UserGroups&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;Page$2&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = '2' or . = '2')]</value>
      <webElementGuid>29c9bfd5-4e65-4ce5-9a50-3320176785d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
