<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ScreenerRecruiter</name>
   <tag></tag>
   <elementGuidId>a03b9db6-e8e1-4782-9fc0-56c18f105b8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dvCBMG_UserGroups_ddlUserType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dvCBMG_UserGroups_ddlUserType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a371125e-5991-4a41-9d33-13b71adbcce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dvCBMG_UserGroups$ddlUserType</value>
      <webElementGuid>6825cbe7-9a44-41ab-a6d9-de88748bb7d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dvCBMG_UserGroups_ddlUserType</value>
      <webElementGuid>ebdfe02d-89fe-4c0b-b208-a0719883af77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8d46550e-7026-4d64-8060-2f09aa8600c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				Screener
				Recruiter

			</value>
      <webElementGuid>00cbfd46-c744-4fbc-b9d7-9c3273e33e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dvCBMG_UserGroups_ddlUserType&quot;)</value>
      <webElementGuid>aac5f21e-e3cd-43e9-b4bb-259129a85c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PostDeployment/ScreenerMaintenance/Set_Screener/Page_247 IRIS - Table Administration/iframe_Table Title_ctl00_ContentPlaceHolder_3b72f3</value>
      <webElementGuid>02cfd0f9-30c7-45bc-88f1-3b0ace93b943</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dvCBMG_UserGroups_ddlUserType']</value>
      <webElementGuid>0488f40b-cbd3-416b-b510-5582050a33fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dvCBMG_UserGroups']/tbody/tr[4]/td[2]/select</value>
      <webElementGuid>f202fdc6-aadc-4a57-91e7-c24cf07068a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Type'])[1]/following::select[1]</value>
      <webElementGuid>77754f3a-f9da-4320-b241-22a66c8d799b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Macapagal, Edessa May T.'])[1]/following::select[1]</value>
      <webElementGuid>d5798d8e-2f49-4be5-95dd-9e82993f5ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is Active'])[1]/preceding::select[1]</value>
      <webElementGuid>9d637261-dcb9-4b00-bd36-421f5a836bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Userid'])[2]/preceding::select[1]</value>
      <webElementGuid>b2498a6b-6c30-42af-bfc1-e4a0be13a3fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3a4a37e2-c789-4ae4-ac51-1c92a61f943b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'dvCBMG_UserGroups$ddlUserType' and @id = 'dvCBMG_UserGroups_ddlUserType' and (text() = '
				Screener
				Recruiter

			' or . = '
				Screener
				Recruiter

			')]</value>
      <webElementGuid>ee75ff4a-05d4-4fbc-a945-3141ce9fcdf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
