<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ApplicantTracking_BIResultsApplicant_b64b89</name>
   <tag></tag>
   <elementGuidId>34e1da63-0e33-44a3-9a12-2432dbfd5835</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ctl00_ContentPlaceHolder1_DropDownList1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_DropDownList1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a788f2e8-b86d-45e7-8de6-8c07d562ad97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$DropDownList1</value>
      <webElementGuid>75dd8c37-9a51-4b0f-bb37-7fdb3ca321e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$ContentPlaceHolder1$DropDownList1\',\'\')', 0)</value>
      <webElementGuid>045a474d-0f69-4b70-8a96-bff9a90e9a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_DropDownList1</value>
      <webElementGuid>59f25077-6c0d-4e66-9147-c4443e6da352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-dropdown</value>
      <webElementGuid>f28b0b85-f8f9-4890-b06e-15c0dae8b04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		ApplicantTracking_BIResults
		ApplicantTracking_CallCenterExp
		ApplicantTracking_CBI_AddtlNotesComments_SubType1
		ApplicantTracking_CBI_AddtlNotesComments_SubType2
		ApplicantTracking_CBI_AddtlNotesComments_Type
		ApplicantTracking_CBI_Competencies_Ratings
		ApplicantTracking_CBI_OverallFit_Ratings
		ApplicantTracking_CBI_OverallRecommendation
		ApplicantTracking_CBI_TMUKValues
		ApplicantTracking_CBTStatus
		ApplicantTracking_ContractType
		ApplicantTracking_Course
		ApplicantTracking_FieldOfStudy
		ApplicantTracking_HighQualifLevel
		ApplicantTracking_Industries
		ApplicantTracking_JobOfferStatus
		ApplicantTracking_JobOfferStatusNew
		ApplicantTracking_MedicalResults
		ApplicantTracking_OCAStatus
		ApplicantTracking_PositionApplied
		ApplicantTracking_PositionLevel
		ApplicantTracking_PositionType
		ApplicantTracking_School
		ApplicantTracking_Sources
		ApplicantTracking_SpecificSources
		ApplicantTracking_Status
		CBMG_UserGroups
		RMS_AcademicConnectors
		RMS_JobFair
		RMS_Online
		RMS_PartnerMgt
		Ropes - Recruitment_Status
		Site

	</value>
      <webElementGuid>ee71f969-cfe1-4700-9072-7a49f15555b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_DropDownList1&quot;)</value>
      <webElementGuid>a7439d77-c599-425f-b0e7-49f212cbd394</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ctl00_ContentPlaceHolder1_DropDownList1']</value>
      <webElementGuid>370e482e-244a-4c25-9f10-0b9398bc7858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_UpdatePanel1']/select</value>
      <webElementGuid>c51941dd-54d4-4986-a644-4787d2e4c2d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Table Administration'])[2]/following::select[1]</value>
      <webElementGuid>59234300-5b48-415e-a196-7c0939256b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name :'])[1]/preceding::select[1]</value>
      <webElementGuid>9e326524-e021-4652-9ec3-6cdd9ab26b6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[1]/preceding::select[1]</value>
      <webElementGuid>c2fac168-69f8-47e3-8113-da6b403367ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>2af8d96a-95e3-4f6a-a004-dceefa63ba4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$ContentPlaceHolder1$DropDownList1' and @id = 'ctl00_ContentPlaceHolder1_DropDownList1' and (text() = '
		ApplicantTracking_BIResults
		ApplicantTracking_CallCenterExp
		ApplicantTracking_CBI_AddtlNotesComments_SubType1
		ApplicantTracking_CBI_AddtlNotesComments_SubType2
		ApplicantTracking_CBI_AddtlNotesComments_Type
		ApplicantTracking_CBI_Competencies_Ratings
		ApplicantTracking_CBI_OverallFit_Ratings
		ApplicantTracking_CBI_OverallRecommendation
		ApplicantTracking_CBI_TMUKValues
		ApplicantTracking_CBTStatus
		ApplicantTracking_ContractType
		ApplicantTracking_Course
		ApplicantTracking_FieldOfStudy
		ApplicantTracking_HighQualifLevel
		ApplicantTracking_Industries
		ApplicantTracking_JobOfferStatus
		ApplicantTracking_JobOfferStatusNew
		ApplicantTracking_MedicalResults
		ApplicantTracking_OCAStatus
		ApplicantTracking_PositionApplied
		ApplicantTracking_PositionLevel
		ApplicantTracking_PositionType
		ApplicantTracking_School
		ApplicantTracking_Sources
		ApplicantTracking_SpecificSources
		ApplicantTracking_Status
		CBMG_UserGroups
		RMS_AcademicConnectors
		RMS_JobFair
		RMS_Online
		RMS_PartnerMgt
		Ropes - Recruitment_Status
		Site

	' or . = '
		ApplicantTracking_BIResults
		ApplicantTracking_CallCenterExp
		ApplicantTracking_CBI_AddtlNotesComments_SubType1
		ApplicantTracking_CBI_AddtlNotesComments_SubType2
		ApplicantTracking_CBI_AddtlNotesComments_Type
		ApplicantTracking_CBI_Competencies_Ratings
		ApplicantTracking_CBI_OverallFit_Ratings
		ApplicantTracking_CBI_OverallRecommendation
		ApplicantTracking_CBI_TMUKValues
		ApplicantTracking_CBTStatus
		ApplicantTracking_ContractType
		ApplicantTracking_Course
		ApplicantTracking_FieldOfStudy
		ApplicantTracking_HighQualifLevel
		ApplicantTracking_Industries
		ApplicantTracking_JobOfferStatus
		ApplicantTracking_JobOfferStatusNew
		ApplicantTracking_MedicalResults
		ApplicantTracking_OCAStatus
		ApplicantTracking_PositionApplied
		ApplicantTracking_PositionLevel
		ApplicantTracking_PositionType
		ApplicantTracking_School
		ApplicantTracking_Sources
		ApplicantTracking_SpecificSources
		ApplicantTracking_Status
		CBMG_UserGroups
		RMS_AcademicConnectors
		RMS_JobFair
		RMS_Online
		RMS_PartnerMgt
		Ropes - Recruitment_Status
		Site

	')]</value>
      <webElementGuid>68e87fac-7a57-412f-8ff7-be2c7ef6f3c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
