<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ApplicantTracking_BIResultsApplicant_b64b89</name>
   <tag></tag>
   <elementGuidId>2ec5e135-bec5-47c3-88eb-920d3de5bafd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ctl00_ContentPlaceHolder1_DropDownList1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_DropDownList1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b8447cd7-e04f-4cf6-82cb-1a8c03ffe584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$DropDownList1</value>
      <webElementGuid>eea3212e-259d-4b41-9076-41f78267e7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$ContentPlaceHolder1$DropDownList1\',\'\')', 0)</value>
      <webElementGuid>03ff87a1-44d2-41c6-9668-ac5898297174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_DropDownList1</value>
      <webElementGuid>aaf57cd8-9515-4b09-8c36-470c836616f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-dropdown</value>
      <webElementGuid>06a2e9e0-b962-4581-9435-93c3d4bbfa00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		ApplicantTracking_BIResults
		ApplicantTracking_CallCenterExp
		ApplicantTracking_CBI_AddtlNotesComments_SubType1
		ApplicantTracking_CBI_AddtlNotesComments_SubType2
		ApplicantTracking_CBI_AddtlNotesComments_Type
		ApplicantTracking_CBI_Competencies_Ratings
		ApplicantTracking_CBI_OverallFit_Ratings
		ApplicantTracking_CBI_OverallRecommendation
		ApplicantTracking_CBI_TMUKValues
		ApplicantTracking_CBTStatus
		ApplicantTracking_ContractType
		ApplicantTracking_Course
		ApplicantTracking_FieldOfStudy
		ApplicantTracking_HighQualifLevel
		ApplicantTracking_Industries
		ApplicantTracking_JobOfferStatus
		ApplicantTracking_JobOfferStatusNew
		ApplicantTracking_MedicalResults
		ApplicantTracking_OCAStatus
		ApplicantTracking_PositionApplied
		ApplicantTracking_PositionLevel
		ApplicantTracking_PositionType
		ApplicantTracking_School
		ApplicantTracking_Sources
		ApplicantTracking_SpecificSources
		ApplicantTracking_Status
		CBMG_UserGroups
		RMS_AcademicConnectors
		RMS_JobFair
		RMS_Online
		RMS_PartnerMgt
		Ropes - Recruitment_Status
		Site

	</value>
      <webElementGuid>737c6f63-8b10-42c5-b999-5f99ae8cc65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_DropDownList1&quot;)</value>
      <webElementGuid>0e688f78-e98d-4f49-b294-7aebed6d9f57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ctl00_ContentPlaceHolder1_DropDownList1']</value>
      <webElementGuid>dd9ad1b1-9b1c-4220-bddb-1827bfd6e9ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_UpdatePanel1']/select</value>
      <webElementGuid>0eee4fd6-662e-4550-9aff-836cbeb283f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Table Administration'])[2]/following::select[1]</value>
      <webElementGuid>284a2caa-8ce9-4bf9-ab77-74e83fb95160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name :'])[1]/preceding::select[1]</value>
      <webElementGuid>b5f01628-1add-4fd2-9f01-56066c8f409c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[1]/preceding::select[1]</value>
      <webElementGuid>a36c900a-fb14-4874-9366-159d09cf07aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>be63c7cb-d1a1-4f6c-b5f8-60bf64b8a80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$ContentPlaceHolder1$DropDownList1' and @id = 'ctl00_ContentPlaceHolder1_DropDownList1' and (text() = '
		ApplicantTracking_BIResults
		ApplicantTracking_CallCenterExp
		ApplicantTracking_CBI_AddtlNotesComments_SubType1
		ApplicantTracking_CBI_AddtlNotesComments_SubType2
		ApplicantTracking_CBI_AddtlNotesComments_Type
		ApplicantTracking_CBI_Competencies_Ratings
		ApplicantTracking_CBI_OverallFit_Ratings
		ApplicantTracking_CBI_OverallRecommendation
		ApplicantTracking_CBI_TMUKValues
		ApplicantTracking_CBTStatus
		ApplicantTracking_ContractType
		ApplicantTracking_Course
		ApplicantTracking_FieldOfStudy
		ApplicantTracking_HighQualifLevel
		ApplicantTracking_Industries
		ApplicantTracking_JobOfferStatus
		ApplicantTracking_JobOfferStatusNew
		ApplicantTracking_MedicalResults
		ApplicantTracking_OCAStatus
		ApplicantTracking_PositionApplied
		ApplicantTracking_PositionLevel
		ApplicantTracking_PositionType
		ApplicantTracking_School
		ApplicantTracking_Sources
		ApplicantTracking_SpecificSources
		ApplicantTracking_Status
		CBMG_UserGroups
		RMS_AcademicConnectors
		RMS_JobFair
		RMS_Online
		RMS_PartnerMgt
		Ropes - Recruitment_Status
		Site

	' or . = '
		ApplicantTracking_BIResults
		ApplicantTracking_CallCenterExp
		ApplicantTracking_CBI_AddtlNotesComments_SubType1
		ApplicantTracking_CBI_AddtlNotesComments_SubType2
		ApplicantTracking_CBI_AddtlNotesComments_Type
		ApplicantTracking_CBI_Competencies_Ratings
		ApplicantTracking_CBI_OverallFit_Ratings
		ApplicantTracking_CBI_OverallRecommendation
		ApplicantTracking_CBI_TMUKValues
		ApplicantTracking_CBTStatus
		ApplicantTracking_ContractType
		ApplicantTracking_Course
		ApplicantTracking_FieldOfStudy
		ApplicantTracking_HighQualifLevel
		ApplicantTracking_Industries
		ApplicantTracking_JobOfferStatus
		ApplicantTracking_JobOfferStatusNew
		ApplicantTracking_MedicalResults
		ApplicantTracking_OCAStatus
		ApplicantTracking_PositionApplied
		ApplicantTracking_PositionLevel
		ApplicantTracking_PositionType
		ApplicantTracking_School
		ApplicantTracking_Sources
		ApplicantTracking_SpecificSources
		ApplicantTracking_Status
		CBMG_UserGroups
		RMS_AcademicConnectors
		RMS_JobFair
		RMS_Online
		RMS_PartnerMgt
		Ropes - Recruitment_Status
		Site

	')]</value>
      <webElementGuid>98ec7589-0ada-4055-b329-5d3a03122393</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
