<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_---Select---ScreenerRecruiter</name>
   <tag></tag>
   <elementGuidId>3fb1eb62-e0d6-4462-a6cb-fd509df843b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dvCBMG_UserGroups_ddlUserType2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dvCBMG_UserGroups_ddlUserType2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>090918a4-c7c6-414a-a13d-5b9c5f173854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dvCBMG_UserGroups$ddlUserType2</value>
      <webElementGuid>5bf73193-8757-4fa8-a042-65aac8ed493d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dvCBMG_UserGroups_ddlUserType2</value>
      <webElementGuid>060ca1ea-70b4-4a12-959f-bace83f2a2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e504fa61-2140-42e0-a455-7407cc74bb66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				&lt;---Select--->
				Screener
				Recruiter

			</value>
      <webElementGuid>34d8c31b-f192-40fd-8dab-7156b6cc331b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dvCBMG_UserGroups_ddlUserType2&quot;)</value>
      <webElementGuid>f737c6d9-d5a4-4100-85fb-7bc533818ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PostDeployment/ScreenerMaintenance/Add_Recruiter/Page_247 IRIS - Table Administration/iframe_Table Title_ctl00_ContentPlaceHolder_3b72f3</value>
      <webElementGuid>337d82c5-2150-41cf-b235-79aa29fb5c56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dvCBMG_UserGroups_ddlUserType2']</value>
      <webElementGuid>bc787628-d8b7-4d40-a99d-75aaeed85182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dvCBMG_UserGroups']/tbody/tr[4]/td[2]/select</value>
      <webElementGuid>5ff768f6-b3c5-4a42-b2de-66369b80659c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Type'])[1]/following::select[1]</value>
      <webElementGuid>26bc857d-6959-45d6-950c-1b0e95351258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Name'])[1]/following::select[1]</value>
      <webElementGuid>e6dc3ab3-1716-4fd3-976e-7da94a8541b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is Active'])[1]/preceding::select[1]</value>
      <webElementGuid>1b6d0255-abdb-46ac-bd20-fee02273bfc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Userid'])[2]/preceding::select[1]</value>
      <webElementGuid>bcf73342-00ca-4045-a1d6-e4aa2ac0c2d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/select</value>
      <webElementGuid>8023601f-6d1a-404a-9312-c81780e710fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'dvCBMG_UserGroups$ddlUserType2' and @id = 'dvCBMG_UserGroups_ddlUserType2' and (text() = '
				&lt;---Select--->
				Screener
				Recruiter

			' or . = '
				&lt;---Select--->
				Screener
				Recruiter

			')]</value>
      <webElementGuid>7df7dde7-a49f-4efc-9ab5-07079a66f497</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
