<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Assigned to Me</name>
   <tag></tag>
   <elementGuidId>ad9d914f-c2fc-42cb-9cda-b9a134fd87c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dropdownAssignment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dropdownAssignment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9e4f5ac0-d534-4f5c-b0b2-5acdc6b61493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>38958462-d582-4fd0-a71a-e6895193cf63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdownAssignment</value>
      <webElementGuid>c93cd1c8-f952-4bed-9d60-c1da5df126d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle btn btn-faded</value>
      <webElementGuid>07b0f006-e5b1-4553-a1eb-7fce8b6c4776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>faaadfea-cf16-48e5-8170-843da3531a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Assigned to Me </value>
      <webElementGuid>f936a0ba-1ff6-40a4-a7be-f4ad804db62a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdownAssignment&quot;)</value>
      <webElementGuid>64fa2d5d-d9e9-4036-aa96-5fc784a527c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='dropdownAssignment']</value>
      <webElementGuid>a48c40ff-d08b-486a-a335-232503920dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignment'])[1]/following::button[1]</value>
      <webElementGuid>e2bd0702-a867-4bdc-bf3f-9519b262266e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non-Agent'])[1]/following::button[1]</value>
      <webElementGuid>b573bcd8-c05e-423d-b7db-3a8c42e2f9b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Applicants'])[1]/preceding::button[1]</value>
      <webElementGuid>86ff1fb4-3c34-4833-b891-cf0277e292cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assigned to Me'])[2]/preceding::button[1]</value>
      <webElementGuid>57061c37-1dbc-4680-a010-6f54f3c98c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Assigned to Me']/parent::*</value>
      <webElementGuid>cf421922-4f31-4d38-b6e8-0a4130ac1a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>8daf8ff7-5cb7-4b29-a663-06ec13749eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'dropdownAssignment' and (text() = ' Assigned to Me ' or . = ' Assigned to Me ')]</value>
      <webElementGuid>9fd60553-cb14-4a53-ac8e-7e8f89ca4067</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
