<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Primary Mobile Number_leads.PrimaryMo_9d0ef2</name>
   <tag></tag>
   <elementGuidId>911bc343-5a11-4e13-ab5c-2744767ccd27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leads_PrimaryMobileNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leads_PrimaryMobileNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb4af11f-e296-4c4d-9082-cffc878b1ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-text form-control-sm</value>
      <webElementGuid>e582ac10-59a2-4513-a87c-4f01286dd9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>39b64d1f-bc29-4254-8593-34eec5a45fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>76239f0d-7e36-4634-9888-e611a996f945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leads_PrimaryMobileNumber</value>
      <webElementGuid>4a1a4b63-77d6-4424-982a-af9067998500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leads.PrimaryMobileNumber</value>
      <webElementGuid>bd5740d8-52c7-4da9-94f6-c5221624b204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>9170000006</value>
      <webElementGuid>12f416f1-e876-4936-9fd9-29e58bfb0117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leads_PrimaryMobileNumber&quot;)</value>
      <webElementGuid>a9e62d3f-8e38-4cfb-a694-872a42373fd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leads_PrimaryMobileNumber']</value>
      <webElementGuid>8cc60ba1-fa28-4bfe-b993-b5870c6289a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appDetailsView']/div[4]/div[6]/input</value>
      <webElementGuid>e7db7b87-21c7-417b-a58e-56314e3dfdf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[6]/input</value>
      <webElementGuid>a54be3db-3442-4d81-ae36-fa9d17479f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'leads_PrimaryMobileNumber' and @name = 'leads.PrimaryMobileNumber']</value>
      <webElementGuid>e642e588-50c6-41a9-936f-4b5af2cf2e1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
