<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Secondary Mobile Number_leads.Seconda_0e7572</name>
   <tag></tag>
   <elementGuidId>f0a41baa-c1b4-4f48-afcc-ce51e6e9920f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leads_SecondaryMobileNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leads_SecondaryMobileNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9056ed29-8dd8-40ae-aa83-d4c8a20de6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-text form-control-sm</value>
      <webElementGuid>3dab4040-c635-4bc6-9036-29849e29a366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>bdbd22ab-5250-4bee-9159-b8621ce8637e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ab4deacf-27c1-479d-b3c9-833ed4562674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leads_SecondaryMobileNumber</value>
      <webElementGuid>4743aca2-dffd-4769-b4bc-3f598aa2966b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leads.SecondaryMobileNumber</value>
      <webElementGuid>10d97480-0198-457e-9dfe-3bf4d5c4d122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leads_SecondaryMobileNumber&quot;)</value>
      <webElementGuid>edd14381-8281-48aa-88b0-0eed00f29afc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leads_SecondaryMobileNumber']</value>
      <webElementGuid>f3d97152-d395-4b27-9080-098336ace64d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appDetailsView']/div[4]/div[7]/input</value>
      <webElementGuid>d4e9af5c-8064-4257-8719-1eb01177a50d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[7]/input</value>
      <webElementGuid>3ac3e8c3-d179-4ff7-bbe2-85eed1ed681f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'leads_SecondaryMobileNumber' and @name = 'leads.SecondaryMobileNumber']</value>
      <webElementGuid>9463470c-90de-4c1a-a643-af63e9f172c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
