<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Home Phone Number_leads.HomePhoneNumber</name>
   <tag></tag>
   <elementGuidId>076d6d49-0a43-4a7b-8178-121875690c79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leads_HomePhoneNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leads_HomePhoneNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53c9c5b5-467b-4db1-a1ef-1964c545a0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-text form-control-sm</value>
      <webElementGuid>c8cc7e8b-8e0d-4f9c-8b48-dbc46b7eb8e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fb19bdb4-ef0d-4643-a768-269020928ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leads_HomePhoneNumber</value>
      <webElementGuid>010c6957-a138-4d88-9231-11f88e1bff44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leads.HomePhoneNumber</value>
      <webElementGuid>f260b4a3-22b1-4ee8-bd97-1f42faf79e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leads_HomePhoneNumber&quot;)</value>
      <webElementGuid>258356db-a967-4bb8-ba93-359df33dd606</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leads_HomePhoneNumber']</value>
      <webElementGuid>39dd4b29-172d-463b-b59e-48ec109a1ccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appDetailsView']/div[4]/div[8]/input</value>
      <webElementGuid>76aaa156-4b70-456a-af8b-cabd0f3ed461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[8]/input</value>
      <webElementGuid>c8d7d55f-05bd-46f5-8db7-98bde8ad7b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'leads_HomePhoneNumber' and @name = 'leads.HomePhoneNumber']</value>
      <webElementGuid>eb4ff3a1-196e-4e1a-a9c4-11d9832d71e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
