<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Table Administration</name>
   <tag></tag>
   <elementGuidId>ceb4d58f-6af1-48b9-9a5f-c876cc588a89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_TreeViewMainMenut34']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_TreeViewMainMenut34</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a32d7cfd-b9ce-4682-8e21-a1f5b4a57cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ctl00_TreeViewMainMenu_0</value>
      <webElementGuid>ca249c69-e079-4a59-9d99-317ddac164c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/webportal/MemberPages/CBMG/CBMG_Tables/TableAdminMain.aspx</value>
      <webElementGuid>09235880-700a-47cd-8bd4-bc09dcff86e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Table Administration</value>
      <webElementGuid>92b0fe1c-6cc0-4b9d-998f-a870331c309d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_TreeViewMainMenut34</value>
      <webElementGuid>52129da0-2027-47fc-8504-bf1810f06536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Table Administration</value>
      <webElementGuid>81cd856a-44d0-4e48-831e-2f39c9cb9923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_TreeViewMainMenut34&quot;)</value>
      <webElementGuid>2fd590f8-b9a2-4de4-b04d-cda632da70a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_TreeViewMainMenut34']</value>
      <webElementGuid>5adcb2f1-1ee7-4b3c-972c-20f5a50b5eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_TreeViewMainMenun0Nodes']/table[9]/tbody/tr/td[4]/a</value>
      <webElementGuid>8567bb3f-05db-4ff4-bfec-e1d6940017ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Table Administration')]</value>
      <webElementGuid>81229213-ef4e-4355-a003-dc0f85871dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ropes Report Last 3 days'])[1]/following::a[2]</value>
      <webElementGuid>1e81cd16-f9af-4d0b-85c9-f07621f6b874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ropes Report'])[1]/following::a[4]</value>
      <webElementGuid>03142fba-4bea-4cf7-ad49-b1ccffd3d674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROPES BOSS'])[1]/preceding::a[2]</value>
      <webElementGuid>cc8ba7d5-99bc-416d-a520-6cdcd3da62f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave Employee Package Tool'])[1]/preceding::a[6]</value>
      <webElementGuid>93974020-4d60-4908-a484-aa8f7683524f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Table Administration']/parent::*</value>
      <webElementGuid>c88c9abc-9e47-48ec-9b1a-74ca775606fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/webportal/MemberPages/CBMG/CBMG_Tables/TableAdminMain.aspx')])[2]</value>
      <webElementGuid>76fb861a-d237-4279-ae1a-60f11dca6e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[9]/tbody/tr/td[4]/a</value>
      <webElementGuid>133fda06-f651-4d02-87b3-f7b6a87c19ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/webportal/MemberPages/CBMG/CBMG_Tables/TableAdminMain.aspx' and @title = 'Table Administration' and @id = 'ctl00_TreeViewMainMenut34' and (text() = 'Table Administration' or . = 'Table Administration')]</value>
      <webElementGuid>8e87a63f-cc9f-4078-8dd5-c4cbe580c35b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
