<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Logout_selectedStatuses</name>
   <tag></tag>
   <elementGuidId>a17a522f-1996-4506-a714-65f2778c17dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selected_status']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selected_status</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3458f4b1-af9d-4be5-b63b-3034f59bdf50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>14c36fa9-056f-481c-adcc-2b10bd453805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectedStatuses</value>
      <webElementGuid>6dd5deaa-e96f-4bfa-b93e-963eecac1bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>All Application Status</value>
      <webElementGuid>0c433db4-1464-4eed-a7a6-d66afe691603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selected_status</value>
      <webElementGuid>7b2f031a-3107-4d79-92ab-754375495a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selected_status&quot;)</value>
      <webElementGuid>e6f1c543-5c2f-414b-9049-5214ba7f7ee9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selected_status']</value>
      <webElementGuid>79524335-5456-4a68-9c98-c6bb1a27164a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmFilterRecipients']/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>58327b72-8f7e-4325-91a5-945099c8aea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>e2a3117b-3508-441d-af12-1689365e0dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'selectedStatuses' and @placeholder = 'All Application Status' and @id = 'selected_status']</value>
      <webElementGuid>0b6ccbcf-16ba-4da3-a5a7-3b2146216ad2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
