<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_12</name>
   <tag></tag>
   <elementGuidId>0baf011b-5c4c-4aca-a743-8afb16d81b18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f6a650bb-c4fc-4859-ab28-f1c8285f397f_cell_selected > a.k-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='f6a650bb-c4fc-4859-ab28-f1c8285f397f_cell_selected']/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '#' and @title = 'Saturday, August 12, 2000' and (text() = '12' or . = '12')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3bb2109c-e62d-4929-a90d-9ef908112d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>17993c0c-37d7-4d2e-b5f9-d062d94c5045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link</value>
      <webElementGuid>4bfe4ba3-7766-4626-b509-8b309af8b746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>98ff5f38-bdb5-45cd-8f6d-4804a2f9dffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>2000/7/12</value>
      <webElementGuid>df20c7dc-e655-4c72-81e0-41a594ed6f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Saturday, August 12, 2000</value>
      <webElementGuid>abb9c384-4a1d-4eaf-b29c-c6887c24c28f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>47e6bf68-ada6-4f41-8992-37577cdb59fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f6a650bb-c4fc-4859-ab28-f1c8285f397f_cell_selected&quot;)/a[@class=&quot;k-link&quot;]</value>
      <webElementGuid>fc26a7fd-cfc7-4864-aee7-d82eb26615c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='f6a650bb-c4fc-4859-ab28-f1c8285f397f_cell_selected']/a</value>
      <webElementGuid>98663759-731c-4eb3-9cef-b6c70b0499bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'12')]</value>
      <webElementGuid>be0674e0-586c-44fd-99a6-10301e706414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::a[14]</value>
      <webElementGuid>e3f2d97b-a06a-45d2-9ca2-cbbe90e63700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::a[14]</value>
      <webElementGuid>9ca819ff-d191-4844-a282-0d85a56e6b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-Select Educational Attainment-'])[2]/preceding::a[30]</value>
      <webElementGuid>63ab6ad0-c736-4551-8d0b-4fd7c65e0978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='select'])[9]/preceding::a[30]</value>
      <webElementGuid>4695cf56-767b-4795-a7ca-3b62d039625c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='12']/parent::*</value>
      <webElementGuid>389afd16-b45f-468a-9de5-d8f3ca745bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[20]</value>
      <webElementGuid>b2b66920-06fc-42c4-98bb-a08c2f665360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[7]/a</value>
      <webElementGuid>3fc760d3-dd5b-458c-b29f-348826ae3964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Saturday, August 12, 2000' and (text() = '12' or . = '12')]</value>
      <webElementGuid>416efd41-1f03-453a-b879-9d8ff3ccbd0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
