<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2020-2029</name>
   <tag></tag>
   <elementGuidId>e4e127cb-50ae-49d2-845e-a6bd44f1486b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.k-link.k-nav-fast.k-state-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='f6a650bb-c4fc-4859-ab28-f1c8285f397f']/div/a[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '#' and (text() = '2020-2029' or . = '2020-2029')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d1de3b69-6828-482c-ad73-5d6704790ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8cb8270b-4a51-41b6-aa0f-f97b4337d513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dec48383-67a4-4d26-8d12-4776e3e1a426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>assertive</value>
      <webElementGuid>6360160f-3d35-4b01-baa2-c44ae5cc0056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>132770c5-deb6-4947-9d1f-b9adab24a1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link k-nav-fast k-state-hover</value>
      <webElementGuid>91ebb9bd-bd50-4ef1-a035-34fe2573805e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4b05d4eb-c047-4121-8766-239f677d685e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2020-2029</value>
      <webElementGuid>eb7f0363-899f-4f7a-9962-6dde01be6b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f6a650bb-c4fc-4859-ab28-f1c8285f397f&quot;)/div[@class=&quot;k-header&quot;]/a[@class=&quot;k-link k-nav-fast k-state-hover&quot;]</value>
      <webElementGuid>9b5c3973-0d5e-450c-a1b6-a420e546add3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='f6a650bb-c4fc-4859-ab28-f1c8285f397f']/div/a[2]</value>
      <webElementGuid>b3766269-35d6-4a01-80d5-c16bfc654502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2020-2029')]</value>
      <webElementGuid>0e0bbc26-2128-4e29-aea7-3e08ff970212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recruitment Assistant - Agent Hiring (Day Shift)'])[1]/following::a[2]</value>
      <webElementGuid>7631e747-536d-4d1c-80d2-a61045b1a2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Network Services Engineer (Flexible Shift)'])[1]/following::a[2]</value>
      <webElementGuid>7674d385-6663-4812-b3a3-96ad8c7c8149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-Select Educational Attainment-'])[2]/preceding::a[15]</value>
      <webElementGuid>aaab7c27-81c3-4e66-9f09-6a60cc3b9927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='select'])[9]/preceding::a[15]</value>
      <webElementGuid>51ca9f49-0a2e-4db3-ad9a-0521ac0013f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2020-2029']/parent::*</value>
      <webElementGuid>c7b0ae83-9705-4426-af48-b78d604e19ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>8ffde23a-e122-41a9-9a40-dbc258121ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a[2]</value>
      <webElementGuid>750fdb14-115f-4853-94f0-42a999d45506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '2020-2029' or . = '2020-2029')]</value>
      <webElementGuid>36d28544-b6c2-4aef-a249-4f88f7e1c2e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
