<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Youtube_c-fymdn5q2efop</name>
   <tag></tag>
   <elementGuidId>fe02f61a-863a-46c0-86dd-bb5e79c45792</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-fymdn5q2efop&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-fymdn5q2efop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>169501c4-df45-4944-b266-6901f63037a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>cbc6862b-36f9-4a82-afff-4a5bddb56930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=mq0-U1BHZ5YTcoDC-CvsLPNc&amp;k=6Ld9GAMTAAAAAOYvz6cI9wF3lpbv5gzcX9n1QxKW</value>
      <webElementGuid>ace2fb30-d56a-47f6-b4d4-6c80e3bdd57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-fymdn5q2efop</value>
      <webElementGuid>fe9268db-bfe3-4d1f-81e4-3045a2fc30d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>776809c5-17f5-43ae-a6f8-3edc0f1d2845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>4a49bb85-21c4-42d5-b5e4-abd8807aea39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>1ccb518a-244e-40ed-9235-8cd603400760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js k-webkit k-webkit104 ng-scope&quot;]/body[@class=&quot;pace-done&quot;]/div[19]/div[4]/iframe[1]</value>
      <webElementGuid>95ffa1ba-f290-49f7-bdde-a7aa825b65c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-fymdn5q2efop']</value>
      <webElementGuid>7a083e8c-3f6c-4e8d-9f41-0571427c6e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>a37e0464-728d-4ecd-acea-09623d3948d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=mq0-U1BHZ5YTcoDC-CvsLPNc&amp;k=6Ld9GAMTAAAAAOYvz6cI9wF3lpbv5gzcX9n1QxKW' and @name = 'c-fymdn5q2efop']</value>
      <webElementGuid>df819fd9-a433-4bc6-b950-63d58845a29f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
