<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Table Title_ctl00_ContentPlaceHolder_3b72f3</name>
   <tag></tag>
   <elementGuidId>3d5fc3ed-5322-4b6c-978c-61c6d40f436d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ctl00_ContentPlaceHolder1_Frame1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_Frame1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>31f643f6-0c95-4259-bf67-4b535fe5f1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_Frame1</value>
      <webElementGuid>463a9de9-bb9e-4036-a3f9-115b4cf41b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1200</value>
      <webElementGuid>ec1b7de4-0a21-40ad-b935-dfe2434b64d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>4a9c15bc-59a1-4981-afdf-f126b6da1a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>CBMG_UserGroups.aspx</value>
      <webElementGuid>6de108c3-7894-4fb2-82a3-cc0ca30d624a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ec1d2b1d-5669-4611-99e2-3b049d0da1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_Frame1&quot;)</value>
      <webElementGuid>14ea2609-9bea-4acd-ac92-c5b5c67f5a73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ctl00_ContentPlaceHolder1_Frame1']</value>
      <webElementGuid>c2fde7e7-2cd4-4174-904e-65d4b97cce60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/table[2]/tbody/tr[4]/td/iframe</value>
      <webElementGuid>d5451d80-28a1-4ea0-9cc0-02c9edbb341b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>5fd04fab-f74b-4545-913a-2e514179bbc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ctl00_ContentPlaceHolder1_Frame1' and @src = 'CBMG_UserGroups.aspx']</value>
      <webElementGuid>32c86cb4-a8fb-42d3-9a01-d98ebdf9afab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
