<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ApplicantTracking_BIResultsApplicant_b64b89</name>
   <tag></tag>
   <elementGuidId>cc27629c-7ae3-452e-aeee-4f6f8c7ac5d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ctl00_ContentPlaceHolder1_DropDownList1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_DropDownList1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8eca5977-7378-4d91-aef8-bccdb61a7f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$DropDownList1</value>
      <webElementGuid>78b92058-b2af-411c-ae20-a4e162a07eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$ContentPlaceHolder1$DropDownList1\',\'\')', 0)</value>
      <webElementGuid>1bcbcdaf-32bd-4ba6-945f-7013bf7dd7dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_DropDownList1</value>
      <webElementGuid>7c644245-ec1e-48ea-ad28-573564609cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-dropdown</value>
      <webElementGuid>bc6c598d-6229-45de-a208-1a0662eabc52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		ApplicantTracking_BIResults
		ApplicantTracking_CallCenterExp
		ApplicantTracking_CBI_AddtlNotesComments_SubType1
		ApplicantTracking_CBI_AddtlNotesComments_SubType2
		ApplicantTracking_CBI_AddtlNotesComments_Type
		ApplicantTracking_CBI_Competencies_Ratings
		ApplicantTracking_CBI_OverallFit_Ratings
		ApplicantTracking_CBI_OverallRecommendation
		ApplicantTracking_CBI_TMUKValues
		ApplicantTracking_CBTStatus
		ApplicantTracking_ContractType
		ApplicantTracking_Course
		ApplicantTracking_FieldOfStudy
		ApplicantTracking_HighQualifLevel
		ApplicantTracking_Industries
		ApplicantTracking_JobOfferStatus
		ApplicantTracking_JobOfferStatusNew
		ApplicantTracking_MedicalResults
		ApplicantTracking_OCAStatus
		ApplicantTracking_PositionApplied
		ApplicantTracking_PositionLevel
		ApplicantTracking_PositionType
		ApplicantTracking_School
		ApplicantTracking_Sources
		ApplicantTracking_SpecificSources
		ApplicantTracking_Status
		CBMG_UserGroups
		RMS_AcademicConnectors
		RMS_JobFair
		RMS_Online
		RMS_PartnerMgt
		Ropes - Recruitment_Status
		Site

	</value>
      <webElementGuid>d1a6f68a-9f03-4d46-bc4b-d314fe43fd6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_DropDownList1&quot;)</value>
      <webElementGuid>291dbe85-bd4b-42ac-bcaa-e8cc1e9eccb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ctl00_ContentPlaceHolder1_DropDownList1']</value>
      <webElementGuid>088c194b-a24e-4200-b6ba-97053a01c341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_UpdatePanel1']/select</value>
      <webElementGuid>6b60a841-e89f-4b5b-b05a-8a626dbdfeed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Table Administration'])[2]/following::select[1]</value>
      <webElementGuid>e9e5a155-66fc-44f5-ba49-923a47f04fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name :'])[1]/preceding::select[1]</value>
      <webElementGuid>b956e832-07e6-46e8-91ac-4136ed4ec8cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[1]/preceding::select[1]</value>
      <webElementGuid>7033e478-86ff-4d00-95ce-26b3ac7ad810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>97211f62-671d-4cae-a1cd-f5b07f649272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$ContentPlaceHolder1$DropDownList1' and @id = 'ctl00_ContentPlaceHolder1_DropDownList1' and (text() = '
		ApplicantTracking_BIResults
		ApplicantTracking_CallCenterExp
		ApplicantTracking_CBI_AddtlNotesComments_SubType1
		ApplicantTracking_CBI_AddtlNotesComments_SubType2
		ApplicantTracking_CBI_AddtlNotesComments_Type
		ApplicantTracking_CBI_Competencies_Ratings
		ApplicantTracking_CBI_OverallFit_Ratings
		ApplicantTracking_CBI_OverallRecommendation
		ApplicantTracking_CBI_TMUKValues
		ApplicantTracking_CBTStatus
		ApplicantTracking_ContractType
		ApplicantTracking_Course
		ApplicantTracking_FieldOfStudy
		ApplicantTracking_HighQualifLevel
		ApplicantTracking_Industries
		ApplicantTracking_JobOfferStatus
		ApplicantTracking_JobOfferStatusNew
		ApplicantTracking_MedicalResults
		ApplicantTracking_OCAStatus
		ApplicantTracking_PositionApplied
		ApplicantTracking_PositionLevel
		ApplicantTracking_PositionType
		ApplicantTracking_School
		ApplicantTracking_Sources
		ApplicantTracking_SpecificSources
		ApplicantTracking_Status
		CBMG_UserGroups
		RMS_AcademicConnectors
		RMS_JobFair
		RMS_Online
		RMS_PartnerMgt
		Ropes - Recruitment_Status
		Site

	' or . = '
		ApplicantTracking_BIResults
		ApplicantTracking_CallCenterExp
		ApplicantTracking_CBI_AddtlNotesComments_SubType1
		ApplicantTracking_CBI_AddtlNotesComments_SubType2
		ApplicantTracking_CBI_AddtlNotesComments_Type
		ApplicantTracking_CBI_Competencies_Ratings
		ApplicantTracking_CBI_OverallFit_Ratings
		ApplicantTracking_CBI_OverallRecommendation
		ApplicantTracking_CBI_TMUKValues
		ApplicantTracking_CBTStatus
		ApplicantTracking_ContractType
		ApplicantTracking_Course
		ApplicantTracking_FieldOfStudy
		ApplicantTracking_HighQualifLevel
		ApplicantTracking_Industries
		ApplicantTracking_JobOfferStatus
		ApplicantTracking_JobOfferStatusNew
		ApplicantTracking_MedicalResults
		ApplicantTracking_OCAStatus
		ApplicantTracking_PositionApplied
		ApplicantTracking_PositionLevel
		ApplicantTracking_PositionType
		ApplicantTracking_School
		ApplicantTracking_Sources
		ApplicantTracking_SpecificSources
		ApplicantTracking_Status
		CBMG_UserGroups
		RMS_AcademicConnectors
		RMS_JobFair
		RMS_Online
		RMS_PartnerMgt
		Ropes - Recruitment_Status
		Site

	')]</value>
      <webElementGuid>7e65834e-52c3-446c-a97c-c6ef9528c054</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
